### ISSUE TITLE
Issue with running multiple examples in fpm version 0.10.1

### ISSUE THREAD

**Issue by gha3mi** [fortran-lang/fpm#1019]
Hi,

In the current version of fpm (version 0.10.1), when executing the command `fpm run --example --all` or `fpm run --example "*"`, only the first example listed in the manifest file is executed.

**Comment by gnikit** [comment]
Duplicate of #1019

**Comment by vmagnin** [comment]
> Duplicate of #1019

Probably an error as the present issue is #1019.

My workaround is to type the list of all examples, e.g.:
```shell
fpm run --example ex1 ex2 ex3 ex4 ex5
```
