### ISSUE TITLE
Issue with running multiple examples in fpm version 0.10.1

### ISSUE THREAD

**Issue by gha3mi** [fortran-lang/fpm#1020]
Hi,

In the current version of fpm (version 0.10.1), when executing the command `fpm run --example --all` or `fpm run --example "*"`, only the first example listed in the manifest file is executed.

[Edited]: I apologize for the confusion. I noticed that I reported the issue in the wrong repository.

**Comment by perazz** [comment]
I just found this is a regression from #1005
