### ISSUE TITLE
Release candidate fpm.F90 uses gfortran-specific backslash line continuations

### ISSUE THREAD

**Issue by sscalpone** [fortran-lang/fpm#1023]
### Description

I pulled fpm.F90 from the [Fpm version v0.10.1](https://github.com/fortran-lang/fpm/releases/tag/v0.10.1) pre-release.

The fpm.F90 source uses backslashes as continuations for a few lines.  This behavior seems to be unique to gfortran and then only when preprocessing is enabled.

I used wget to pull this file:
```
https://github.com/fortran-lang/fpm/releases/download/current/fpm.F90
```
See the backslashes:
```
28745     call run('git archive '//ref//' &
28746         --format='//archive_format// &
28747         add_files//' \
28748         -o '//destination, \
28749         echo=verbose, \
28750         exitstat=stat)
28751     if (stat /= 0) then
28752       call fatal_error(error, "Error packing '"//source//"'."); return
28753     end if
28754   end
```

### Expected Behaviour

The code would use standard fortran continuation lines.

### Version of fpm

Fpm version v0.10.1

### Platform and Architecture

Linux

### Additional Information

```
% cksum fpm.F90
3410678574 1553216 fpm.F90
```

**Comment by henilp105** [comment]
fixed in #1024.
