### ISSUE TITLE
bug(ci): uploaded artefacts not pinned to specific GCC version

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/fpm#1044]
With the introduction of multiple GCC versions in our CI/CD pipelines we ended up in a situation where the upload/download artefacts have the same name and consequently the upload/download (v3) GitHub Actions would pick the last created artefact as the one to be listed in our CD and Release Notes. Which artefact is generated last varies from run to run.

This currently works because there are no (major?!) ABI changes between GFortran 10 through 12, however we can't expect this to always be the case.

This issue was originally uncovered as part of the dependabot PR https://github.com/fortran-lang/fpm/pull/985, where now upload artefacts **must** have unique names.

I propose that for the time being the artefacts that we provide as part of our CD are based on the oldest supported version of GFortran, in this case GFortran-10. @awvwgk and @perazz any thoughts on this?

This should get fixed as part of  https://github.com/fortran-lang/fpm/pull/985.

**Comment by awvwgk** [comment]
Can we include the compiler version in the artifact name? For the upload we can specify which compiler version we want exactly.

**Comment by gnikit** [comment]
> Can we include the compiler version in the artifact name? 

Yes, my changes should already be in effect in the dependabot PR.

> For the upload we can specify which compiler version we want exactly.

Yes, that's my thinking as well. Should we choose the oldest GCC version for that?
