### ISSUE TITLE
Implicit interface not working with lfortran

### ISSUE THREAD

**Issue by davidpfister** [fortran-lang/fpm#1047]
### Description

I have a code using implicit interfaces (.. yes, I know, but it can be handy), that I tried to compile with lfortran. For this, I use the options directly inside the toml
```toml
[fortran]
implicit-external = true
```
and I get the following message: 
```
The following argument was not expected: --allow-implicit-interface
```

Looking at the command lines from lfortran it seems that the argument shoud be ```--implicit-interface```

### Expected Behaviour

This error should not appear.

### Version of fpm

0.10.0 alpha

### Platform and Architecture

Windows 10

**Comment by awvwgk** [comment]
The option for LFortran is specified at

https://github.com/fortran-lang/fpm/blob/6b18ae5be06ccafbde849634bfa35a231a6e7110/src/fpm_compiler.F90#L238

Feel free to sent a patch for updating this to the right option in LFortran.
