### ISSUE TITLE
Error when building new app on Windows with ifort.

### ISSUE THREAD

**Issue by rodeoboy** [fortran-lang/fpm#1065]
### Description

Start by creating a new Fortran project using fpm.
`fpm new my-app`
Try to build the project and I get the following error.
```
$ fpm build --compiler ifort --flag "-fpp"
mkdir build\dependencies
my-app.f90                             done.
libmy-app.a                            failed.
[ 50%] Compiling...
'lib' is not recognized as an internal or external command,
operable program or batch file.
<ERROR> Compilation failed for object " libmy-app.a "
<ERROR> stopping due to failed compilation
STOP 1
(base)
```

It seems to be prepending 'lib' onto my project name and trying to compile a file named "libmy-app.a". This is also happening on a project that I tried to convert to using fpm. I tried creating a project from scratch to see if I could debug the problem, but I got the same error in both cases.

### Expected Behaviour

build successfully.

### Version of fpm

0.10.1

### Platform and Architecture

Windows 11

### Additional Information

Using the Intel Fortran compiler  Version 19.0.5.281 Build 20190815

**Comment by drannex42** [comment]
Did you ever figure it out? having the same issue with gfortran.

**Comment by perazz** [comment]
Please check this out: 

https://fortran-lang.discourse.group/t/lib-is-not-recognized-as-an-internal-or-external-command-operable-program-or-batch-file/8661
