### ISSUE TITLE
'lib' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by jacobwilliams** [fortran-lang/fpm#1066]
### Description

There is some issue on Windows when using gfortran. (i'm using the win-64 binaries from here: https://anaconda.org/conda-forge/gfortran/ )

For example, when trying to compile json-fortran:

```
fpm test --compiler gfortran
```

getting this error message:

```
json_kinds.F90                         done.
json_parameters.F90                    done.
json_string_utilities.F90              done.
json_value_module.F90                  done.
json_file_module.F90                   done.
json_module.F90                        done.
libjson-fortran.a                      failed.
[  6%] Compiling...
'lib' is not recognized as an internal or external command,
operable program or batch file.
<ERROR> Compilation failed for object " libjson-fortran.a "
<ERROR> stopping due to failed compilation
STOP 1
```

### Expected Behaviour

compile it

### Version of fpm

0.10.0, alpha

### Platform and Architecture

Windows 10

**Comment by jacobwilliams** [comment]
Nm... Looks like 'lib' is the windows `msvc` version of `ar`? I guess getting that installed is out of scope for an fpm issue. will close.

**Comment by jacobwilliams** [comment]
note for the future: that conda package installs `gcc-ar` which seems to work. you have to call it like so:

```
fpm test --compiler gfortran --archiver gcc-ar
```

**Comment by perazz** [comment]
This is where the logic is implemented: 

https://github.com/fortran-lang/fpm/blob/4030a8ad4e77a64decee51ea02790d948e075dbb/src/fpm_compiler.F90#L1064-L1075

**Comment by jacobwilliams** [comment]
Wonder if it should just also try gcc-ar too by default if Fortran is the compiler?
