### ISSUE TITLE
Projects including legacy files

### ISSUE THREAD

**Issue by ivan-pi** [fortran-lang/fpm#107]
I've been trying to get fpm to work with some old-school packages like MINPACK: https://github.com/certik/minpack. These projects are generally just a bunch of fixed format ".f" files. For modern applications that rely on such legacy codes, an interface module is the first step towards safe function calls.

Trying to run `fpm build` on @certik's MINPACK fails with errors akin to:
```
fpm build --release
# gfortran (for build/gfortran_release/minpack/rwupdt.o build/gfortran_release/minpack/rwupdt.mod)
# gfortran (for build/gfortran_release/minpack/dmchar.o build/gfortran_release/minpack/dmchar.mod)
# gfortran (for build/gfortran_release/minpack/lmpar.o build/gfortran_release/minpack/lmpar.mod)
# gfortran (for build/gfortran_release/minpack/hybrd.o build/gfortran_release/minpack/hybrd.mod)
fpm: Error when running Shake build system:
  at want, called at src/Build.hs:205:11 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
* Depends on: build/gfortran_release/minpack/libminpack.a
  at need, called at src/Build.hs:203:13 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
* Depends on: build/gfortran_release/minpack/rwupdt.o
  at &%>, called at src/Build.hs:183:11 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
* Depends on: build/gfortran_release/minpack/rwupdt.o build/gfortran_release/minpack/rwupdt.mod
  at error, called at src/Development/Shake/Internal/Rules/Files.hs:245:13 in shake-0.18.5-44KSA7uQF2VObxzEvLYZx:Development.Shake.Internal.Rules.Files
* Raised the exception:
Error, &%> rule failed to produce 1 file (out of 2)
  build/gfortran_release/minpack/rwupdt.o
  build/gfortran_release/minpack/rwupdt.mod - MISSING
```
I understand that fpm is expecting to find a module file for each single ".f" file. Is it possible to somehow work around this? The farthest I could get it in the fpm source was to remove to the "-Wimplicit-interface" flag which was creating lots of warnings :see_no_evil: .

Am I right to think fpm is currently most suitable for projects composed of multiple module files?

**Comment by LKedward** [comment]
I was playing around with gtk-fortran and I found a work-around for non-module sources by renaming them to `.in` files so that `fpm` ignored them and including them with the `include` statement in a module.

It's not ideal and I'm not sure what the plan is for supporting non-module sources but I think they should be supported in some form.

Perhaps the larger question is whether we will make `fpm` flexible enough to support legacy packages in their original form or require restructuring of such packages; this latter option is not as extreme as it sounds since for some packages, `fpm` support will be brought through a third-party fork anyway (_i.e._ not via the upstream repo).

**Comment by everythingfunctional** [comment]
At the moment, `fpm` is only really targeted at projects with modules. At some point we may support non-module sources, but it may be some time before we get to it.

@LKedward , clever workaround. I may even suggest that as a recommended migration path.

In the mean time, there is always the out that `fpm` now supports custom build scripts or Makefiles (with some specific requirements).

**Comment by certik** [comment]
We have to support non-module sources. But this might be a feature to put into the Fortran based fpm to keep the Haskell based on minimal to be used in bootstrapping.
