### ISSUE TITLE
fortran main name file

### ISSUE THREAD

**Issue by lauvergn** [fortran-lang/fpm#116]
I found an issue related to the name of the main fortran file.
When main.f90 is in the app directory, the executable is created nicely. Part of the fpm.toml file is:
> [[executable]]
> name="TEST_dnS.x"
> source-dir="app"
> main="main.f90"

However, when, I'm using another name (TEST_dnS.f90)
> [[executable]]
> name="TEST_dnS.x"
> source-dir="app"
> main="TEST_dnS.f90"

I've got some errors:
>fpm: Error when running Shake build system:
>  at want, called at src/Build.hs:114:11 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
> * Depends on: build/gfortran_debug/app/TEST_dnS.x
>  at need, called at src/Build.hs:120:13 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
> * Depends on: build/gfortran_debug/app/test_dns.o
>  at &%>, called at src/Build.hs:137:11 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
> * Depends on: build/gfortran_debug/app/test_dns.o build/gfortran_debug/app/test_dns.mod
>  at undefined, called at src/Build.hs:142:25 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
>  at error, called at libraries/base/GHC/Err.hs:78:14 in base:GHC.Err
> * Raised the exception:
> Prelude.undefined

**Comment by everythingfunctional** [comment]
That looks to me like it's expecting a `test_dns` module. Perhaps there is a uppercase/lowercase mismatch in the file name? Maybe try deleting the build directory to start fresh?

I can maybe try and dig deeper later today if none of those work.

**Comment by lauvergn** [comment]
> Perhaps there is a uppercase/lowercase mismatch in the file name?

I thought about that too, but it is not that.

> Maybe try deleting the build directory to start fresh?

I've tried that as well (several times!!)

**Comment by lauvergn** [comment]
> I can maybe try and dig deeper later today if none of those work.

Thanks, you can get the full test here: 

https://github.com/lauvergn/test-fpm

**Comment by everythingfunctional** [comment]
Figured out the problem. The build process for the executable isn't handling upper-case vs lower-case correctly for the name of the source file vs the name of the object file. I'll get a fix put together shortly.

**Comment by lauvergn** [comment]
> Figured out the problem. The build process for the executable isn't handling upper-case vs lower-case correctly for the name of the source file vs the name of the object file. I'll get a fix put together shortly.

Thanks

**Comment by lauvergn** [comment]
Thnanks
