### ISSUE TITLE
"name" should not be a required fpm.toml keyword for files that do not link to an fpm library

### ISSUE THREAD

**Issue by MarkWieczorek** [fortran-lang/fpm#120]
In the current configuration, it is necessary to specify a `name` keyword at the top of the fpm.toml file. This name is used to name the directory that contains the .mod, .a, and .o files that are used to generate a static library. 

However, if you have a project with only a single file in the `app` folder, there is no need to have a `src` folder nor to compile a library at all. In this case, however, if you omit the `name` keyword, fpm will exit with the error `tomland decode error:  Key name is not found`

Furthermore, in my opinion, the `name` keyword should not be at the head of the file, but should more logically be under the `[library]` heading, as this is where all the information about the compiled archive is listed. (This would be analogous to `name` in `[[executable]]`).

**Comment by certik** [comment]
If you create a new package with Cargo, say `cargo new y`, then you get the following `Cargo.toml`:
```
[package]
name = "y"
version = "0.1.0"
authors = ["Ondřej Čertík <ondrej@certik.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```
So the name is simply the name of the package. Even if it is just a simple executable. So I think the `name` should stay, it's the name of the project.

**Comment by everythingfunctional** [comment]
`name` is used as the default for many things, so you do need it. Otherwise, you'd need to be explicit about everything and likely repeat yourself, which we're trying to avoid for common use cases.

**Comment by MarkWieczorek** [comment]
If that is the case, shouldn't

```
[[executable]]
name =
```
be set by default to `name`? If you don't set the executable name, you get a similar error.

Encountering this project for the first time, it wasn't really obvious what the parameters in the fpm.toml file mean. In addition to this, there is also
```
[library]
source-dir
```
which is the directory for files used to compile .mod and .a files. However
```
[[executabe]]
source-dir
```
Corresponds only to the name of the directory in `build/gfortran_debug`  where you find the compiled executable.

**Comment by everythingfunctional** [comment]
Yeah, we haven't worked through all of the possible combinations of `fpm.toml` inputs and under what combinations defaults should work. For example

```toml
[[executable]]
source-dir = "app1"
```

should probably work with the "defaults" for `name` and `main`, but

```toml
[[executable]]
source-dir = "app1"

[[executable]]
source-dir = "app2"
```
would need to complain about conflicting names for the executables.

The documentation almost certainly needs work and clarification.

**Comment by LKedward** [comment]
There is now a [manifest reference](https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md) detailing the contents for `fpm.toml` and, as explained above, the `name` key is preferred as a top level entry to refer to the overall project. I will now close this issue.
