### ISSUE TITLE
Not so trivial program: Fortran with a bit of C and a prebuilt library

### ISSUE THREAD

**Issue by arjenmarkus** [fortran-lang/fpm#125]
After this month's call, I looked for a small but not entirely trivial program to try fpm with (not trivial in the sense that it consists of several source files, rather than a single one). I found one that is a trifle more complex than any of the examples I have seen and I would like advice on how to deal with it:
- It consists of several Fortran source files and a single C source file
- Some of the Fortran source files require preprocessing (the extension is .F90, so some compilers will do that automatically)
- The program needs to be linked to a (C) library that has been installed on the system

The trivial way I build it is via a bunch of compile commands with the required options, so ultimately that could function as a custom build script, but the above set-up seems a fairly common situation.

**Comment by everythingfunctional** [comment]
With current functionality, your only option for this is a custom build script. At some point in the future we'll have the capabilities built into fpm to handle linking to a system library and (hopefully) compiling C code, but we aren't there yet.

**Comment by arjenmarkus** [comment]
I understand - I already thought that would be the answer :). Consider it another likely scenario that - at some point in time - needs to be supported..

**Comment by awvwgk** [comment]
This should be possible with Fortran *fpm* now, as we support compiling C code there and linking with external libraries.
