### ISSUE TITLE
Command line interface (CLI)

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#135]
How to implement the CLI in fpm-fortran? We can use:

* Intrinsics `command_argument_count` and `get_command_argument` (lowest level, no dependencies)
* [FLAP](https://github.com/szaghi/FLAP) by @szaghi (library, pure Fortran, I've used it a bit with good experience)
* [M_cli](https://github.com/urbanjost/M_cli) by @urbanjost (library, pure Fortran, no personal experience with it)
* Some other library I'm not aware of?

I think we should go with a library and both FLAP and M_cli seem to do what we need (positional arguments + optional flags). What do you think?

**Comment by certik** [comment]
I would go with FLAP. But we have to make it an fpm package first, so that we can use it as a dependency.

**Comment by milancurcic** [comment]
M_cli is already an fpm package (I tried it--it works). However, after reviewing M_cli in more detail, I'm quite strongly in favor of FLAP. It seems more mature and powerful while in my opinion having a simpler API. 

@szaghi would you accept a PR to FLAP that would make it an fpm package? We'd make sure that your existing build systems  (CMake, Make, Fobis) still work. This would require adding an fpm.toml file to the top-level directory, and some adjustments to module names or source file names, but otherwise it would be backward compatible from user's point of view. Best part, it would make FLAP part of a rapidly growing fpm ecosystem of packages.

**Comment by everythingfunctional** [comment]
I haven't had a chance to look at either of the libraries, but that is definitely the way to go. We need to do whatever can help us bootstrap this faster.

Note: the command line for fpm is quite complicated; subcommands, flags that are only applicable for a subset of them, some flags which may be mutually exclusive, etc.

I think the first step, before we start implementing the command line interface is to clearly spec it out. Then we can pick a library and start implementing.

**Comment by ivan-pi** [comment]
I am aware of two more libraries for command line interfaces:
* [command_args](http://flibs.sourceforge.net/command_args.html) from @arjenmarkus 
* [FTN_Getopt](https://doku.lrz.de/dyn/Doku_Kurse/Fortran/getopt/) by Reinhold Bader (author of FGSL). I like the simplicity of this one (it is a single module). Unfortunately, the source code is not publicly available at the moment. I have a copy of the code and the author has indicated to me I can share it under GPL and the condition of preserving the authorship.

**Comment by certik** [comment]
I would like all fpm dependencies to be MIT or BSD licensed, because we are linking everything statically into one executable, so GPL (and even LGPL) would prohibit us to license fpm under the MIT license.

**Comment by jvdp1** [comment]
Wouldn't it be useful to integrate such a library first (or simultaneously) in `stdlib`?

**Comment by ivan-pi** [comment]
One more library I learned of recently is [libSUFR](https://github.com/MarcvdSluys/libSUFR/tree/master/examples) (libSUFR is a library containing Some Useful Fortran Routines). It is also GPL.

The M_cli module from @urbanjost is licensed under the Unlicense. The way I understand the licensing system of FLAP:

>     for FOSS projects:
>         GPL v3;
>     for closed source/commercial projects:
>         BSD 2-Clause;
>         BSD 3-Clause;
>         MIT.

fpm would count as a FOSS project, since the source is public. Am I correct?

**Comment by milancurcic** [comment]
> fpm would count as a FOSS project, since the source is public. Am I correct?

I think that strictly only GPL family of software is FOSS. We are just OSS :)

I'm pretty sure that @szaghi meant "use whatever license you want". He can confirm this.

**Comment by certik** [comment]
@jvdp1 yes, `stdlib` should have basic command line parsing, just like Python has it. But we can wait with stdlib's integration until we get more experience what API makes the most sense.

**Comment by ivan-pi** [comment]
Just as an alternative idea, we could also wrap one of the many existing C and C++ libraries:
* [docopt.c](https://github.com/docopt/docopt.c), [docopt.cpp](https://github.com/docopt/docopt.cpp)
* [commander](https://github.com/clibs/commander)
* [CLI11](https://github.com/CLIUtils/CLI11) (I noticed @certik is a contributor :+1: )
* [cxxopts](https://github.com/jarro2783/cxxopts)

I think with the current Haskell version of fpm, this would require a custom Makefile.

**Comment by certik** [comment]
Yes, I investigated all options for C++, and most of them work, and I settled with using CLI11 for LFortran. Works great.
