### ISSUE TITLE
Roadmap for Fortran implementation

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#136]
## Please see our [beta release milestone](https://github.com/fortran-lang/fpm/milestone/1) for the latest roadmap for the Fortran implemetation.
This was discussed recently during the October monthly call ([fpm-update-october-2020.pdf](https://github.com/fortran-lang/fpm/files/5451317/fpm-update-october-2020.pdf))

**Comment by milancurcic** [comment]
Fortran interface to curl for http requests: https://github.com/interkosmos/fortran-curl

If we end up needing more advanced git stuff then just downloading the code, we can wrap [libgit2](https://libgit2.org/).

**Comment by milancurcic** [comment]
## TOML parsers

I found 2, both support TOML v0.5 spec:

* [toml-f](https://github.com/awvwgk/toml-f) which is pure Fortran, but unfortunately GPLv3-licensed. We could ask the author to offer a more permissive license beside GPL.
* [f_tomlc99](https://github.com/gregfi/f_tomlc99) which interfaces a C parser. MIT-licensed.

So each presents an integration challenge.

**Comment by certik** [comment]
Per my comment in https://github.com/fortran-lang/fpm/issues/149#issuecomment-663703530, it seems all of these can in principle be done in pure Fortran, except the internet download of tarballs. For git repositories, we'll just assume that the `git` executable is installed, as we already do in haskell fpm. To be able to bootstrap fpm easily, we can just have all dependencies as git repositories and assume `git` is present on all platforms. Then in principle everything can be done in pure Fortran, which I think might be very helpful at least initially.

Then we can implement robust support for 3rd party non Fortran dependencies in the fortran fpm. Eventually we can then depend on `curl` or any other library.

**Comment by jacobwilliams** [comment]
FYI...somewhere i have a Fortran interface to [WinINet](https://docs.microsoft.com/en-us/windows/win32/wininet/about-wininet) that i wrote years ago. I think it was pretty rudimentary but it could be used to download files (on windows only of course). I can dig that up, but maybe you just want to stick with curl on all platforms?

**Comment by awvwgk** [comment]
Closing this in favor of the milestone.
