### ISSUE TITLE
How to list directory content

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#141]
In order to move beyond #137, we need a cross-platform way to read all the `*.f90` files in a directory. What is the best way to do that in Fortran?

**Comment by milancurcic** [comment]
For cross-platform you need [this](https://github.com/fortran-lang/stdlib/issues/220).

Otherwise, I think the next best kludge would be to `call execute_command_line('ls > tmp.txt')`, then parse `tmp.txt`, and equivalent on Windows.

**Comment by certik** [comment]
We need a temporary solution so that we are not stuck on this, and can move on, and in the meantime we can work on the full general solution.

**Comment by milancurcic** [comment]
I agree. I think wrapping around the shell commands on each OS is the way to go.

**Comment by certik** [comment]
It seems like it. How do you determine which OS you are on from Fortran?

**Comment by milancurcic** [comment]
Perhaps we can test the value of an environment variable (`get_environment_variable') that we know will be different between systems? Perhaps HOME, and then detect based on whether the value has forward slashes (Linux and macOS) or backslashes (Windows)? Just an idea, I've never done this myself.

**Comment by certik** [comment]
Good idea, the `GET_ENVIRONMENT_VARIABLE` intrinsic will do this. That will get us started, and we can make this more robust / general later.

**Comment by everythingfunctional** [comment]
I'd put it behind a function and just use preprocessor directives. Something like:

```fortran
function is_windows()
    logical :: is_windows

#ifdef (WIN_32)
    is_windows = .true.
#elif
    is_windows = .false.
#endif
```

Obviously you'll need to look up the proper syntax and tests, but that way, even if you change the way it's done, it shouldn't require changing any other code anywhere.

**Comment by certik** [comment]
@everythingfunctional ah that's right, I think that should work.

**Comment by milancurcic** [comment]
I didn't know fpm supported preprocessing. :+1: in that case.

**Comment by everythingfunctional** [comment]
fpm isn't doing any preprocessing, but our currently only supported compiler does a bit ;). Should be enough to solve at least the "Is this Windows or not?" question.

**Comment by arjenmarkus** [comment]
I just tried: on Windows "dir /b" gives the bare list of file names, just as "ls". That means that only the command is different - not the format of the output (with out "/b" you get a lot of rubbish ;)).

**Comment by certik** [comment]
@everythingfunctional so the ifdef trick does not work with gfortran to determine the OS, I tried that in https://github.com/fortran-lang/fpm/pull/142, and it does not work on linux, nor anywhere else...

**Comment by certik** [comment]
Thanks @arjenmarkus. I will try to do this once #142 is merged, as I need to determine the OS type first to know which command to run.

**Comment by interkosmos** [comment]
Until _stdlib_ can be included, perhaps linking an ISO C binding abstraction layer to either [POSIX](https://cyber.dabamos.de/programming/modernfortran/file-system-directories.html) and Win32 routines at compile time may be sufficient.

**Comment by awvwgk** [comment]
This has been resolved by https://github.com/fortran-lang/fpm/pull/507
