### ISSUE TITLE
`fpm run` does not propagate exit code

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#143]
`fpm run` does not return with error if the program fails, as can be checked by:
```
$ fpm run && echo "OK"
ERROR STOP 

Error termination. Backtrace:
#0  0x7ff9ae8262ed in ???
#1  0x7ff9ae826ed5 in ???
#2  0x7ff9ae827f86 in ???
#3  0x55ee5e99e013 in get_os
	at src/fpm.F90:22
#4  0x55ee5e99df25 in __fpm_MOD_print_help
	at src/fpm.F90:28
#5  0x55ee5e99daa2 in MAIN__
	at app/main.f90:7
#6  0x55ee5e99dc43 in main
	at app/main.f90:2
OK
```
This causes CI tests to pass even though they should fail, e.g.:

https://github.com/fortran-lang/fpm/pull/142/checks?check_run_id=897192409

which should have failed, but happily continues:
```
...
# gfortran (for build/gfortran_debug/app/main.o)
# gfortran (for build/gfortran_debug/app/fpm)
+ fpm run
ERROR STOP 

Error termination. Backtrace:
#0  0x7fc9615aaaed in ???
#1  0x7fc9615ab605 in ???
#2  0x7fc9615acc93 in ???
#3  0x55b23ed92014 in get_os
	at src/fpm.F90:22
#4  0x55b23ed91f21 in __fpm_MOD_print_help
	at src/fpm.F90:28
#5  0x55b23ed91a7d in MAIN__
	at app/main.f90:7
#6  0x55b23ed91c28 in main
	at app/main.f90:2
+ fpm run --args build
 # Building project
 + gfortran -c src/fpm.F90 -o fpm.o
 + gfortran -c app/main.f90 -o main.o
...
```

This is quite high priority, as we need our CI to be reliable with regards to these things.

@everythingfunctional do you  know how to fix it?

**Comment by everythingfunctional** [comment]
I see. I expected the function used to run external commands to propagate that automatically, but I guess I was wrong. It should just be a matter of catching the return status and manually doing something with it. I should have some time to look into it this weekend.
