### ISSUE TITLE
fpm should detect operating system

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#144]
Given the issues in #141 to determine the OS type, I think the most robust is to do it like CMake: fpm will detect / know the operating system that it is on, and it will pass this information down the source files, for example in terms of macro definitions, such as:

* `FPM_OS_LINUX`
* `FPM_OS_MACOS`
* `FPM_OS_WINDOWS`

Or something like that. We might be even more specific than that if needed. This seems to be the most robust and cross-platform way to do it that will work with all Fortran compilers.

**Comment by certik** [comment]
I tried various ways using macros in #142, and none of them seem to work with gfortran. So that's why I think having fpm define those macros is the way to go.

**Comment by milancurcic** [comment]
Right, so if fpm itself can detect the operating system, what do you need the macros for? I thought the macros are only useful when your software doesn't have the information you need. Or am I missing something?

**Comment by certik** [comment]
It's a chicken and an egg. The fpm implementation in Fortran needs to know the system type so that we know what command to use to get the directory content. The most robust seems to be if the build system (whether cmake or fpm) passes this information in as macro definitions.

**Comment by milancurcic** [comment]
Okay, so the bootstrap fpm will know the OS and pass the macros down to Fortran fpm. Then in the future when you want to bootstrap Fortran fpm using Fortran fpm, then the OS information will already be available in the boostrap Fortran fpm. It made me dizzy for a little bit, but I think it works.

**Comment by certik** [comment]
Right. The other way to bootstrap fpm down the road will be via cmake (#123), so the cmake build system that fpm will generate will have to detect the OS type (which cmake knows how to do) and then create the proper `FPM_OS_*` macro defines.

**Comment by arjenmarkus** [comment]
You could use the commands that come with the operating system (for instance [this website](https://www.computerhope.com/whow.htm) gives some indicators. 
While this will not be waterproof, the module may simply test the various commands - whichever succeeds is the one we want.
I can give this a try.

**Comment by arjenmarkus** [comment]
I just tried:
ver in a Windows command box gives the indication of the Windows version
This does not work with MinGW or Cygwin, even though they are Windows-based OSes.
uname -a succeeds on MinGW, Cygwin and Linux with proper indications of all OS types.
I have no access to MacOS but I imagine that uname -a work fine there as well.
(Something to check: whether ver is not a haphazard program - for uname I guess /usr/bin/uname is restrictive enough?)

**Comment by certik** [comment]
Here is how we currently do this using environment variables: https://github.com/fortran-lang/fpm/blob/6ef25462797940d7b8323551545a4726e1c90b1b/fpm/src/fpm.f90#L16

**Comment by arjenmarkus** [comment]
Hm, the environment variable HOMEPATH is set to "\Users\markus" on my Cygwin and MinGW/w-64 installations. So, with the current procedure that would boil down to "Windows".

**Comment by milancurcic** [comment]
It looks like we may have to combine the current HOMEPATH query with a `ver` test suggested by @arjenmarkus if we want to differentiate MinGW or Cygwin from Windows.

**Comment by arjenmarkus** [comment]
Since they represent very different operating environments, I think we
cannot ignore the difference ;). For instance: "dir" does not work under
Cygwin or MinGW.

Regards,

Arjen

Op do 23 jul. 2020 om 19:20 schreef Milan Curcic <notifications@github.com>:

**Comment by arjenmarkus** [comment]
Oops, I was too hasty: "dir" does actually work and "dir -b" also. But then
"dir /b" does not and, vice versa, under a Windows command box "dir -b"
does not work - it looks for a file "-b".

Regards,

Arjen

Op do 23 jul. 2020 om 19:22 schreef Arjen Markus <arjen.markus895@gmail.com

**Comment by milancurcic** [comment]
Right, [dir](https://www.gnu.org/software/coreutils/manual/html_node/dir-invocation.html) is part of GNU Coreutils, so it works on most Linux systems, but not on macOS for example. Best to stay away from it for making important decisions :).

**Comment by arjenmarkus** [comment]
I have experimented a bit: the attached code correctly identifies the
four OSes I have access to. It cannot rely on "ver", because that is
also supported by MinGW and Cygwin, so instead I use "uname". However,
MinGW gives odd results - /usr/bin/uname was not found (presumably the
directory is not properly substituted). So, it also tries "uname"
without the path.

The executable I created with Intel Fortran gives the right (!)
identification under a Windows command box, MinGW and Cygwin. I have
not tested the MinGW/Cygwin variants under the others.

(Attaching it to an email was the fastest way, but of course I can
also put it in a pull request)

Regards,

Arjen

Op do 23 jul. 2020 om 19:34 schreef Milan Curcic <notifications@github.com>:
>
> Right, dir is part of GNU Coreutils, so it works on most Linux systems, but not on macOS for example. Best to stay away from it for making important decisions :).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

! getos.f90 --
!     Attempt to characterise the operating system
!
module getos
    implicit none

    integer, parameter :: OS_WINDOWS = 1
    integer, parameter :: OS_LINUX   = 2
    integer, parameter :: OS_MACOS   = 3
    integer, parameter :: OS_CYGWIN  = 4
    integer, parameter :: OS_MINGW   = 5

contains

! get_os --
!     Identify the operating system
!
! Arguments:
!     None
!
! Note:
!     Linux is used as the fallback option. Should we distinguish this from a positive identification?
!
integer function get_os()
    character(len=80) :: val
    character(len=20) :: os_id
    integer           :: lun
    integer           :: stat

    !
    ! Try the environment variable
    !
    call get_environment_variable( "HOMEPATH", val, status = stat )

    if ( stat == 0 .and. val(1:7) == "\Users\" ) then
        !
        ! We may be on Windows, probably, but what flavour? Windows, Cygwin or MinGW?
        !
        ! First try "uname"
        !
        ! Note: MinGW gives an error when using the full path ...
        !
        call execute_command_line( "/usr/bin/uname -a > fpm_tmp.out 2>&1", exitstat = stat )
        if ( stat /= 0 ) then
            call execute_command_line( "uname -a > fpm_tmp.out 2>&1", exitstat = stat )
        endif

        if ( stat /= 0 ) then
            !
            ! This seems to be Windows
            !
            get_os = OS_WINDOWS
        else
            open( newunit = lun, file = "fpm_tmp.out" )
            read( lun, * ) os_id
            close( lun, status = 'delete' )

            get_os = merge( OS_CYGWIN, OS_MINGW, os_id(1:6) == 'CYGWIN' )
        endif
    else
        !
        ! We are on Linux or MacOS
        !
        call get_environment_variable( "HOME", val, status = stat )

        if ( stat == 0 ) then
            if ( val(1:7) == "/Users/" ) then
                get_os = OS_MACOS
            else
                get_os = OS_LINUX
            endif
        else
            !
            ! Use Linux as fallback option
            !
            get_os = OS_LINUX
        endif
    endif
end function get_os

end module getos

! test ...
!
program test_get_os
    use getos

    integer :: id

    character(len=10), dimension(5) :: os_identification = &
        ['Windows   ', 'Linux     ', 'MacOS     ', 'Cygwin    ', 'MinGW     ']

    id = get_os()
    write(*,*) id, os_identification(id)

end program test_get_os

**Comment by certik** [comment]
Thanks @arjenmarkus, much appreciated. We should incorporate this into fpm.

**Comment by awvwgk** [comment]
Done with #162
