### ISSUE TITLE
examples with multiple executables and tests

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#152]
I had created fpm.toml files that worked, but apparently were not correct toml files. With help from @LKedward I changed my list of executables to an array in several fpm.toml files which now passes tests as standard toml and still works; but when I try the same syntax with multiple test programs my tests are ignored. It is probably something simple but it took me a while just trying empirically to get everything running initially with multiple programs (realizing each one had to be in a seperate directory and so on). I was thinking I am not the only one likely to have these problems and that a more extensive example on this site showing the proper/preferred way to have multiple test programs and application executables would help avoid the problem and give me a solution. The first use I have made of TOML is for these fpm files so even if I get something to work I am not particularly confident it will be the "right" way.

**Comment by certik** [comment]
Thanks for reporting the issue. I agree we need better examples and tests.

**Comment by arjenmarkus** [comment]
I have the same set-up for the collection of modules I called "pointsets" -
with each test program in a separate directory, but the sources for the
modules in one and the same source directory. This works fine. If you need
an example (for at least the current way), you could use that.

Regards,

Arjen

Op zo 16 aug. 2020 om 02:02 schreef Ondřej Čertík <notifications@github.com

**Comment by LKedward** [comment]
> when I try the same syntax with multiple test programs my tests are ignored.

Hi @urbanjost, this may be a subtle problem with the ordering of your `fpm.toml` file - does the inline array definition of `test` come after any previous (non-inline) array definition such as `[[library]]` or `[[executable]]`, if so then the resulting data structure will have `test` as a sub-member of the previous definition and will hence be ignored at the top-level. This is IMO, an unfortunate subtlety of how [Array of tables](https://toml.io/en/v1.0.0-rc.1#array-of-tables) are defined in `toml`.

**Comment by urbanjost** [comment]
That was the major problem! Thanks. Still tweeking it but this particular module is primarily an interface to C POSIX routines. It is at least working again; although still tweeking it.  

    git clone https://github.com/urbanjost/M_system.git

     >>fpm.toml <<
     [dependencies]
     M_system        = { git = "https://github.com/urbanjost/M_system.git" }

Still think some vetted examples here would be useful, of course.

**Comment by LKedward** [comment]
> Still think some vetted examples here would be useful, of course.

Agreed. It would also be useful to mention the alternative compact notation for array-of-tables - useful for multiple executables/tests - and the above limitation.
