### ISSUE TITLE
Add a contributing guideline

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#158]
This project is currently missing resources for to learn about the preferred workflows or the style guide. At least for me a contributing guideline is a strong factor I consider before contributing to a project. In my opinion it helps set the right expectations and cuts down the noise in PRs required to educate new contributors.

It would be nice to have at least a short guideline in the README or in a separate CONTRIBUTING file to establish some rules for this project.

**Comment by everythingfunctional** [comment]
That's a great idea. Any chance you could put one together for us?

**Comment by milancurcic** [comment]
For reference, here's what we have in [stdlib](https://github.com/fortran-lang/stdlib/blob/master/WORKFLOW.md). 

What do you think about something along the lines of:

1. Open an issue to discuss the scope of the changes, API if applicable, etc.;
2. Reach consensus;
3. Open a PR with the changes, while following the fpm style guide (TODO);
4. Request 1-3 reviewers on the PR.

**Comment by everythingfunctional** [comment]
I don't see any major issues with that one. If other contributors agree, I'd be fine with adopting it.

**Comment by LKedward** [comment]
I have no problem with your contributor guide @awvwgk but can you add a section like '__Workflow__' which incorporates what Milan posted? I would also add the following to the workflow:

- After reaching consensus on an issue discussion, assign the issue to yourself to indicate to others that you have started work on that issue to avoid duplicate effort
