### ISSUE TITLE
Support registry meta-data fields in manifest

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fpm#165]
Now that we have fpm-registry I think we should add official support for various meta-data fields in the `fpm.toml` manifest including `description`, `keywords`, `categories`, and `homepage`.

Looking to `cargo` as an example, it requires [the following fields](https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate) before a crate can be published.

Checking and validating the fields is a job for the fpm-registry CI, this issue is just to enable support within fortran `fpm`.

**Comment by awvwgk** [comment]
It would require a schema definition or at least any kind of documentation what is allowed in a package manifest, `description` is actually missing in the PACKAGING.md, which I took as reference for the allowed keys.

Also the two available implementation follow very different strategies. The boostrap implementation ignores everything except the needed keys, while the Fortran implementation does not allow anything except the keys hardcoded in the executable.

**Comment by awvwgk** [comment]
I think adding all those keywords to the toplevel might overload the package file a bit, having additional sections for meta information would probably be best, *e.g.* conda-build is using `about`. We could support an `extra` section as well, which is not governed by any schema and allows to test new sections or keys.

**Comment by awvwgk** [comment]
Done with #171.
