### ISSUE TITLE
Build failing due to SSL error at get.haskellstack.org

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#184]
This URL fails to download (even in a browser for me right now) due to some SSL error:

https://get.haskellstack.org/stable/windows-x86_64.zip

And so our CI tests currently fail.

@everythingfunctional what do you think we should do?

We can host the Haskell binaries ourselves for our CI tests.

**Comment by LKedward** [comment]
> We can host the Haskell binaries ourselves for our CI tests.

This makes sense; we already do this for the OSX binary right?

**Comment by certik** [comment]
That's right, I forgot about that! 

I won't have time to work on this, but if anyone can upload the Windows and Linux binaries somewhere, so that we can change the links, that would be awesome.

**Comment by LKedward** [comment]
Happy to do it! I just need to find another place to download them from other than haskellstack.org...

**Comment by certik** [comment]
@LKedward thank you, that would be a huge help!

**Comment by LKedward** [comment]
I've found binaries on the stack github page:
https://github.com/commercialhaskell/stack/releases/tag/v2.3.3

I could just replace the download links in the CI workflow file with these? Or would you prefer if we hosted them ourselves?

**Comment by certik** [comment]
Let's just replace them for now. I think the GitHub links should be stable.

**Comment by LKedward** [comment]
It looks like haskellstack.org now working again, and the main CI is now passing but I will still open a pull request to replace the stack urls with those from git.

**Comment by everythingfunctional** [comment]
I think there's an aspect of having one more thing to maintain if we have our own "mirror" for the stack binaries, and I don't know if I'd ever expect to have this problem again. You can do it if you want, but I don't know that it's necessary. Whatever you guys think.

**Comment by certik** [comment]
Well, I had to upload the macOS binary in the past precisely for this problem. So this is the second time happening, so unfortunately I expect it to happen again.

This issue has been fixed by #185.
