### ISSUE TITLE
Should files created by "fpm new" only be placeholders or more substantive?

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#192]
When you run "fpm new" it creates placeholder files. They are essentially "hello world" examples. That keeps it simple but I was wondering if a more substantive file might be useful, especially for programmers new to Fortran or unit testing. Maybe a link to the stdlib logging/testing topics in a WRITE statement, ...

But thinking of something like the following:
```fortran
program main
implicit none
integer                    :: A = 10,  B = 20,  C = 30,  i
logical,allocatable        :: tally(:)
logical                    :: allpassed = .true.
character(len=*),parameter :: gen = "(*(g0:, 1x))"
character(len=*),parameter :: fancy = "(a, *(""[""g0,"":"",g0,""]"":))"
   write(*,"(a)")"SAMPLE TEST PROGRAM - Put some real tests in here!"
   ! determine if a group of tests all pass
   allpassed = allpassed .and. a < b .and. b < c
   allpassed = allpassed .and. annotate( "IS A.LT.B?", a < b )
   allpassed = allpassed .and. annotate( "IS B.LT.C?", b < c )
   allpassed = allpassed .and. annotate( "IS A.LT.C?", a < c )
   write(*,"(a)")merge("EVERYTHING PASSED","SOMETHING FAILED ",allpassed)
   ! append results of tests into TALLY
   tally = [ logical :: ]
   tally = [ tally, a < b ]
   tally = [ tally, c < b ]
   tally = [ tally, b < c .and. a < c ]
   ! show test results
   write(*, fmt=fancy)"testing tally=", (i, tally(i), i = 1, size(tally))
   if( all(tally) )then
      write(*, gen)"PASSED: all", size(tally), "tests passed"
   else
      write(*, gen)"FAILED: out of", size(tally), "tests",   &
       & count(.not.tally), "failed and", count(tally), "passed"
   endif
contains
   function annotate(msg, tst)
   character(len=*),intent(in) :: msg
   logical,intent(in)          :: tst
   logical                     :: annotate
      annotate=tst
      write(*, "(a,1x,l1)" )msg,tst
   end function annotate
end program main
```
Just throwing the thought out there.  Maybe the README.md file could have something in it too, like:

**This project uses the Fortran Package Manager**
                 
The home page for fpm(1) is                    
    [http://github.com/fortran-lang/fpm](http://github.com/fortran-lang/fpm)
                 
Registered fpm(1) packages can be found at         
    [http://fortran-lang.org/packages/](http://fortran-lang.org/packages/)
                 
Discuss Fortran at                    
    [https://fortran-lang.discourse.group/latest](https://fortran-lang.discourse.group/latest)
                 
Contribute to the Fortran Standard Library at      
    [https://github.com/fortran-lang/stdlib](https://github.com/fortran-lang/stdlib)
                 
Find this and more at the [Fortran Language](https//github.com/fortran-lang) page

But markdown is not exactly portable, so not sure links would always work and user might not even be usiing a web repository

**Comment by awvwgk** [comment]
I like the idea of a more elaborate README. Advertising resources for Fortran might be interesting, maybe more helpful would be a short introduction on fpm, from building over running tests to finally installing the project, if it is well written, it might stay in the README of the finally published project as building instructions.

As for the scaffold of the executable or library, the less the better, chances that an example code will fit the users project are rather small, in my opinion.

But I can see, that giving fpm the capability to work as a cookiecutter for creating a new project, when giving the correct template, could reduce some repetitive work. Maybe we could allow fpm to create a new project from a template repository.
