### ISSUE TITLE
system call to git(1) as a preliminary remote dependency method for Fortran fpm?

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#199]
Since git(1) is being assumed as an installed package and being used to do an initial new project in both versions of fpm(1) would it be reasonable to use a git(1) system call in f-fpm to pull remote dependencies so that all base functions are available?
This would allow the f-fpm version to have basic full functionality (build,run,test,new) and allow for completing prototypical development of all of the lbase ocal platform features.  Thoughts?

**Comment by everythingfunctional** [comment]
That's exactly what the Haskell version is doing, so I'd be in favor of it, at least for now.

**Comment by urbanjost** [comment]
Did not realize that but that certainly goes a long way toward proving it would work!

**Comment by urbanjost** [comment]
Does h-fpm then make a recursive call to h-fpm to build it as well when it builds the remote packages?

**Comment by everythingfunctional** [comment]
It doesn't launch a new process, but fetching and building the dependencies is a recursive procedure.

**Comment by everythingfunctional** [comment]
See [`bootstrap/src/Fpm.hs`](https://github.com/fortran-lang/fpm/blob/0c35749e0d90b5de43a7a90eb47677695e5c81e2/bootstrap/src/Fpm.hs#L540) lines 540 - 677 for how it's done.

**Comment by LKedward** [comment]
Based on this I've now added support for remote git dependencies in #193, since it only requires a small addition.

**Comment by urbanjost** [comment]
Fantastic. Between the f-toml interface and the work you have done on building all the fun stuff has progressed so dramatically it looks like it will be able to bootstrap itself very soon.

**Comment by urbanjost** [comment]
I might just need to update, but seem to have trouble with files that have "include" as part of the filename.

$ ffpm build
Parse error: unable to find include file name
test/demo_include.f90:6
   |             includes
ERROR STOP 7

Error termination. Backtrace:
#0  0x7ff909aa7131 in ???
#1  0x7ff909aa7cd9 in ???
#2  0x7ff909aa8e9b in ???
#3  0x4141de in __fpm_MOD_cmd_build
        at src/fpm.f90:141
#4  0x401977 in MAIN__
        at app/main.f90:22
#5  0x401a20 in main
        at app/main.f90:8
[urbanjs@localhost fortran-intrinsic-manpages]$

**Comment by LKedward** [comment]
Closing as implemented in #193
