### ISSUE TITLE
Supported compilers to build fpm

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#205]
What range of compilers should Fortran fpm support to build itself? Question is more regarding GCC version, but we could also discuss how Intel, PGI, NAG, ... compilers should work together with Fortran fpm. Of course this requirements for Fortran fpm becomes strict requirements for all dependencies used in Fortran fpm as well.

For example, if we want to distribute fpm with common toolchains like homebrew and conda-forge, we will have drastic limitations on the GCC version we can use:

- homebrew: GCC 5
- conda-forge: GCC 7.5

Supporting GCC 5 can be hard, because many features are missing. GCC 7.5 sounds reasonable to me, even if it means we might have to workaround some know ICE or bug at some point.

**Comment by LKedward** [comment]
I agree, 7.5 should be doable as a minimum version. I've been using 7.5.0 on Ubuntu without any problems so far. Versions prior to 7 would be too restrictive IMO.

**Comment by everythingfunctional** [comment]
I don't think we should concern ourselves too much with supporting older compilers. I don't think most people will need or want to compile it from scratch. Most would prefer an installer, or a single executable. I think the goal for fpm should be to supply packages for the most common package managers. I.e.

* yum
* apt
* pacman
* homebrew
* Windows installer (maybe?)
* Windows package manager (I know there are one or two but I'm not familiar with them)

**Comment by certik** [comment]
Also:
* Conda
* Spack

**Comment by awvwgk** [comment]
The other thing is CI support, for OSS we can easily cover GCC 5 to 10 and Intel 20 as well as PGI 20.7, at least I already setup CI's for those.

> Windows package manager (I know there are one or two but I'm not familiar with them)
[choco](https://chocolatey.org/) and [nuget](www.nuget.org)

**Comment by awvwgk** [comment]
Got the first GCC migrator on my conda-forge feedstocks today, so the cf toolchain will in future be GCC 9.3. I will have a look at homebrew again, maybe they migrate from GCC 5 at some point as well.

**Comment by awvwgk** [comment]
Since we started packaging I think this issue has kinda resolved itself. We will just package for toolchains that are recent enough to support building fpm.

**Comment by certik** [comment]
> Since we started packaging I think this issue has kinda resolved itself.

Best kind of issues. :)

Yes, many things do resolve themselves like this.
