### ISSUE TITLE
Doc Workflow Fails

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#240]
The doc workflow introduced in #237 appears not to be working. @awvwgk , any chance you can take a closer look and find out what went wrong? You can find the workflow that failed [here](https://github.com/fortran-lang/fpm/actions/runs/366538276).

**Comment by milancurcic** [comment]
Same with stdlib API docs.

**Comment by 14NGiestas** [comment]
The fpm workflow uses this one [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action), funny thing I have to fix it there.

**Comment by 14NGiestas** [comment]
I just bumped the version to the latest one and it seemed to work, can someone please verify if it fixes the issue?

**Comment by LKedward** [comment]
Closed with #241
