### ISSUE TITLE
Suggest including short arguments for the major long subcommand options [fortran fpm]

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#243]
Currently the syntax of f-fpm subcommands sans --help and
--version consists of the following:
```text
    build [--release] [--list] [--flag COMPILER_OPTIONS]
    help [NAME(s)]
    new NAME [--lib|--src] [--app] [--test] [--backfill]
    list [--list]
    run [NAME(s)] [--release] [--runner "CMD"] [--list] [-- ARGS]
    test [NAME(s)] [--release] [--runner "CMD"] [--list] [-- ARGS]
```
Suggest allowing short names as well as long names at least for
the most commonly interactively used options, as in
```text
    build [--release|-r] [--list|-l] [--flag|-f COMPILER_OPTIONS]
    help [NAME(s)]
    new NAME [--lib|-l|--src|-s] [--app|-a] [--test|-t] [--backfill|-b]
    list [--list|-l]
    run [NAME(s)] [--release|-r] [--runner|-c "CMD"] [--list|-l] [-- ARGS]
    test [NAME(s)] [--release|-r] [--runner|-c "CMD"] [--list|-l] [-- ARGS]
```
That is,

       --app, `-a`
       --backfill, `-b`
       --help, `-h`
       --lib, `-l`
       --list, `-l `
       --release, `-r`
       --runner, `-c`
       --src, `-s`
       --test, `-t`
       --version, `-v`

Looking at `cargo` it allows short names for several options, but not all.
Some commands like `stack` appear to only allow a few short options, like
-j and -v. Some commands like `git` allow a lot of short options. In git's case it is only
for the more common options on each subcommand; but  note git(1) has an elaborate aliasing
scheme that allows users to make aliases; including an internal scripting
language.

**Comment by awvwgk** [comment]
Adding short flags should be done sparsely, while it might be convenient we only got a limited amount of them. I would favour a more careful design of the command line arguments in the first place, arguments that are expected to be used frequently should be easier/shorter to type.
