### ISSUE TITLE
Command line bug on Windows

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fpm#254]
Running `fpm --version` (or `fpm --help`) on Windows using the [latest release build](https://github.com/fortran-lang/fpm/releases/tag/v0.1.0) (`fpm-v0.1.0-windows-x86_64.exe`) produces the following error:
```
UNKNOWN LONG KEYWORD: --version
KEYWORD  SHORT PRESENT VALUE
               F        [F]
```

No such error occurs on Linux. ~I believe this regression was introduced in #239 where the `M_CLI2` [revision was updatded](https://github.com/fortran-lang/fpm/pull/239/files#diff-8ef5c67414adfda95d21898e4c6a91e80d92a975ae36ba897cfc7543dcb8c8ae).~

@urbanjost, are you able to look into this?

**Comment by LKedward** [comment]
Okay I've tracked it down to the use of compiler optimisation.

The following will work and print help information: `fpm run --flag -O0 -- --help`, however any non-zero level of optimisation (`-O1`,`-O2`,`-O3`) will fail with the above error message.

@urbanjost, it looks like the command line interface is possibly relying on some undefined behaviour which is causing issues when compiled with optimisation flags on Windows.

---

We should add tests on the release version in our CI.

**Comment by urbanjost** [comment]
Have not been able to reproduce it on Red Hat, so will need to install mingw on a MSWindows machine. Hopefully that will be straight
forward.

**Comment by urbanjost** [comment]
Installed three versions of minogw and also tried in Cygwin, and Cygwin with mingw added and  just running the M_CLI2 tests themselves independent of ffpm (on ifort, nvfortran, and gfortran)
and I cannot reproduce the problem just building the fortran part. I will try to set up the machine to have the Haskell setup instead of directly compiling the fortran parts.  It did not sound like the problem would require that to duplicate but I have been unable to duplicate it so far.

**Comment by LKedward** [comment]
Have you tried the `mingw-w64 8.1.0` build available [here](http://mingw-w64.org/doku.php/download/mingw-builds) on plain Windows (same as used in our CI). I'm able to reproduce on a separate Windows machine with this mingw-w64 version using the latest master branch built from scratch.

```
c:\>gcc --version
gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
```

After building from scratch (delete output folder), with bootstrap `fpm` I get:
```
c:\msys64\home\laure\git\fpm3\fpm>fpm run --release -- --version
UNKNOWN LONG KEYWORD: --version
KEYWORD  SHORT PRESENT VALUE
               F        [F]
```
As per my previous comment this appears to be a problem that only occurs with compiler optimization flags hence `'--release'`.

**Comment by LKedward** [comment]
@urbanjost, I believe I've tracked it down to the `split(3f)` function used both in `M_CLI2` and in the `fpm_strings` module. There appears to be a compiler bug with `mingw-w64-gcc 8.1.0` whereby the `case (:high)` syntax for the `select case` clause is not correctly implemented.

I find replacing `'case (:0)'` with `'case (0)'` fixes the issue:
```
diff --git a/src/M_CLI2.f90 b/src/M_CLI2.f90
index 7f95e31..d022a52 100644
--- a/src/M_CLI2.f90
+++ b/src/M_CLI2.f90
@@ -3071,7 +3071,7 @@ integer                       :: imax                   ! length of longest toke
 !-----------------------------------------------------------------------------------------------------------------------------------
    select case (ilen)
 !-----------------------------------------------------------------------------------------------------------------------------------
-   case (:0)                                                      ! command was totally blank
+   case (0)                                                      ! command was totally blank
 !-----------------------------------------------------------------------------------------------------------------------------------
    case default
```

**Comment by LKedward** [comment]
I've created a PR at <https://github.com/urbanjost/M_CLI2/pull/4>. If you are happy with it, after merging I will open a subsequent PR in this repo with an update revision for `M_CLI2` and the same fix applied in the `fpm_strings` module.

**Comment by urbanjost** [comment]
Thanks. Had not had time to look at this further till now. Looks like you have a general solution.  Looking at it now.
