### ISSUE TITLE
Use fpm as an test package in the CI

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fpm#272]
As [discussed](https://github.com/fortran-lang/fpm/pull/271#pullrequestreview-545643873), we should build, run and test fortran fpm using fortran fpm in the CI just like we do with the existing example packages.

**Comment by awvwgk** [comment]
I'll take care of this once https://github.com/fortran-lang/fpm/pull/352 is merged.

**Comment by LKedward** [comment]
Closing since implemented via #420.
