### ISSUE TITLE
Make Fortran binaries appear first in the list of release assets

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#276]
https://github.com/fortran-lang/fpm/releases

Currently we have:

* fpm-bootstrap-v0.1.1-linux-x86_64
* ...
* fpm-v0.1.1-linux-x86_64
* ...

Assets are sorted alphabetically, so fpm-bootstrap-* binaries come first. It's possible that, not knowing the difference, some users will reach for the bootstrap binaries first. Instead, we should gear them toward the Fortran binaries first, although it has shown recently that [it's useful to have both](https://fortran-lang.discourse.group/t/runge-kutta-code-reuse-fpm/463), due to bugs and incomplete features on both sides. 

I recommend that we have the Fortran binaries appear first at the list of assets.

An easy fix would be to drop the "v" from the semantic version because it's the "v" that makes the Fortran binaries come after the Haskell ones. "v" is not that common anyway--you're more likely to see something like gcc-9.3.0 than gcc-v9.3.0.

Also, related to #253, considering that the "bootstrapping" property is no longer unique to the Haskell fpm, I suggest we just distribute these as fpm-haskell-* instead of fpm-bootstrap-*, to minimize confusion.

**Comment by LKedward** [comment]
Good points, I agree with you on all three. This should be a relatively simple change to the CI.

**Comment by LKedward** [comment]
<https://github.com/fortran-lang/setup-fpm/> which will also need updating (also simple).
