### ISSUE TITLE
Enable discussions for this repository?

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#278]
GitHub discussions is now in public beta and might be a suitable addition for discussion on *fpm* separated from the issues. It is currently opt-in at the settings tab of the repo.

This might overlap slightly with what we are currently using issues for and also maybe with the Fortran-lang discourse.

**Comment by milancurcic** [comment]
Good idea, I support it. fpm discussions on the Discourse so far were, I think, due to not there being any dedicated place to discuss fpm specifically. 

We can enable it. Before we do, has anybody had experience with it? Is it ready for prime time?

**Comment by awvwgk** [comment]
I have seen it around at some other more popular repos, but not used it in my projects so far. I just enabled it at http://github.com/grimme-lab/xtb/discussions.

**Comment by milancurcic** [comment]
I just enabled it. I think I will like it. Worst case scenario, if it doesn't work for any reason, we turn it off.
