### ISSUE TITLE
name collision between  example/main.f90 and app/main.f90

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#305]
Files built with the `test` command go into build/*/test/ and with the `run` command into  build/*/app but files built from the example/
directory also go into the app/ directory.  The files are built with their object files named after their original filenames, so if you have
test/main.f90 and app/main.f90 .  But if you add example/main.f90
it gets placed in the same place as the app files, so you cannot build because there is a filename collision.

There are a few approaches.  The examples could be build in an example/ subdirectory in build like test  (probably the simplest) or they could be built with their target name  (which in this case is different in the fpm.toml file) or the pathname where they were found could be used to build the file,  or the user can just rename a source file and it can be left as-is.

On a related note,  you add the  --example switch to `run` to  build examples, but have the test command to run tests.  So far test and run have not diverged in functionality.   I would suggest  that we add --test to the `run` command and then add an `example` command and change the documentation for `test`  to say it is just an alias for `run --test`  and add a new command called `example` and say it is just an alias for  `run --example`. As it is there is the inconsistency on how to run test applications versus example applications,  but I strongly prefer using `test` versus `run --test` and would prefer a command called `example` versus `run --example`.  

I also wonder if there should be an --app switch. The default would be --app if none of the three are specified, perhaps?  That way
if you wanted you could run all of them with run --app --example --test, although I am not sure that is required(?).  In general I run them one at a time myself. and would be fine with removing the --example switch from run and having a separate command as is now the case with `test` called `example`.

I would expect a `fpm.toml` file like
```text
 name = "A"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "2020 Jane Doe"

[build]
auto-executables = false
auto-tests = false
auto-examples = false

[library]
source-dir="src"

[[test]]
name="runTests"
source-dir="test"
main="main.f90"

[[example]]
name="runExample"
source-dir="example"
main="main.f90"

[[executable]]
name="A"
source-dir="app"
main="main.f90"
```
to work even without turning off the auto build, as it does now for a test and and app; but it does not. Certainly with no auto builds I thought it would.  Otherwise we need to indicate such collisions must be avoided by the user, which till now we have protected them from.

**Comment by awvwgk** [comment]
The same happens with a project using a setup like

```toml
name = "collision"

[[executable]]
name = "exe1"
source-dir = "app1"
main = "main.f90"

[[executable]]
name = "exe2"
source-dir = "app2"
main = "main.f90"
```

Running Fortran *fpm* we get:

```
 Error while building target list: duplicate output object "build/gfortran_debug/app/main.f90.o"
  Source file: "app2/main.f90"
STOP 1
```

**Comment by awvwgk** [comment]
> On a related note, you add the --example switch to `run` to build examples, but have the test command to run tests. So far test and run have not diverged in functionality. I would suggest that we add --test to the `run` command and then add an `example` command and change the documentation for `test` to say it is just an alias for `run --test` and add a new command called `example` and say it is just an alias for `run --example`. As it is there is the inconsistency on how to run test applications versus example applications, but I strongly prefer using `test` versus `run --test` and would prefer a command called `example` versus `run --example`.

I thought about an example as a special kind of runable target, therefore I grouped it with `run --example` to the run command.  The equivalent for a testable target might be a benchmark which would nicely fit into the current scheme with `test --benchmark`.

**Comment by LKedward** [comment]
Thanks both for reporting the two collision cases. I think I know where this needs to be fixed, I'll have a go at a fix tomorrow.

**Comment by urbanjost** [comment]
It seems more consistent to me to have  `run  [--test|--benchmark|-example|--app] and have corresponding directories test/, benchmark/, example/, and app/ as special pre-defined directories,  or to have run  app/ example/ where instead of programs being selected a directory could be selected, where if the name contains a separator it is assumed to be a directory.  I would call my examples more "test" than "app" so I would not look for them under `run`  I would look under `test`.  I think allowing directory names as a name would be the most general in that it would allow a user to target a grouping of their own category, and alleviates having to alter the `fpm.toml` file each time a different  program is selected. And since `test` is just such a case when nothing is specified in the TOML file it seems relatively natural.  Of course,  I think I could have all the sources in a single directory and explicitly specify everything in the TOML file  as to what is test,  example, and app (but I have not actually tried that).  

If I was a new user I think `run` being able to run any executable would be the most intuitive, and names like test, bench, example would be nice additions but mean I only have to read one command description and do not have to look around for how to run a file.

Except (probably) for compiler directives I think as much should work as possible without anything but a simple metadata TOML file,
and that editing the TOML file should only be required for someone building a complex project.  I think Fortran more than any other language is used as a tool by non-programmers  but ironically has less pre-built tools. So I am picturing someone that knows how to 
compile a program, use a text editor, and knowing maybe a little git or hg or CVS being able to use fpm(1) without having at first learn about CMake, Make, ar,  exotic compiler options, ... . It seems easier to tell someone who wants to run a program to use `run`; and if they have tests, benchmarks, and examples there is a nice shortcut available.  Got to admit there is a lot personal baggage in deciding that.   I tend to think of what would be the simplest to explain to someone that had never heard of it and go from there though.

**Comment by arjenmarkus** [comment]
Well, this was certainly one reason to write the minibook on building
programs in the first place :). And on the various forums (fora?) I see
enough questions that suggest that the poster is indeed a member of that
category. So let us keep that scenario in mind indeed.

Op ma 14 dec. 2020 om 22:45 schreef urbanjost <notifications@github.com>:

**Comment by LKedward** [comment]
> It seems more consistent to me to have `run [--test|--benchmark|-example|--app]` and have corresponding directories test/, benchmark/, example/, and app/ as special pre-defined directories

This seems like a good idea to me but while also keeping `fpm test` as an alias for `fpm run --test` since having a test command is a common expectation. I prefer this to adding more top-level commands for `benchmark` and `example`.

**Comment by everythingfunctional** [comment]
> It seems more consistent to me to have `run [--test|--benchmark|-example|--app]` and have corresponding directories test/, benchmark/, example/, and app/ as special pre-defined directories

I think this is very similar to the design that cargo and stack ended up with. I'd have to double check to be sure. So basically:
* `fpm run` implies `fpm run --app`
* `fpm test` implies `fpm run --test`

**Comment by urbanjost** [comment]
Internally basically `test` is a special case of `run`;  unless that is going to change that simplifies documentation and usage.
The question is whether anyone wants the commands to diverge. In some other packages `test` is totally different than `run` and implies the use of a specific testing framework, in others it is an alias for `run` with a switch, as proposed and as is (currently) true in `fpm`.  So currently now you read about the `run` command and then read about the `test` command and there is no difference except which list of executables they select, based on the directory the tests are in or the categories they have been placed in (executable or test) in the TOML manifest. If the documentation is largely redundant it seems the command is too, except that those options are so commonly used they deserve an abbreviation. 

So does anyone intend `test` to become a completely different beast?  I find it does what I want in its current form.
