### ISSUE TITLE
Create plugin system for extending `fpm` from 3rd party packages

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#313]
This was first mentioned here:

https://github.com/fortran-lang/fpm/discussions/309#discussioncomment-219589

The idea is that people are already writing many 3rd party tools for everything from formatting, automatic documentation lookups, pre-processors, etc. Many of these tools require to understand the structure of the project, which `fpm` knows and can provide to them, so that `lfortran fmt` can format your whole project, it would get the list of files from `fpm`.

It could go the other way too, so that `fman` can register a new command `fpm man`, which would look up things, or `lfortran` can register `fpm fmt`. Similar to how `git` can be extended by simply providing a tool `git-something` in a `$PATH` and `git something` becomes available. 

The way various Jupyter kernels register with jupyter is that they simply create a file in `$PREFIX/share/jupyter/kernels/fortran/kernel.json`, which creates a `fortran` kernel. So in the same way, `fman` can install a file `$PREFIX/share/fpm/plugins/fman/plugin.json` which has information where to find `fman` and anything else needed for `fpm` to be able to call it. The way this works with `Jupyter` is that you just install `lfortran` (say using `conda install lfortran`) and it will automatically appear in Jupyter as an optional kernel, users do not have to do anything, it just works.

Let's brainstorm this more.

**Comment by awvwgk** [comment]
See https://github.com/fortran-lang/fpm/issues/211 for a previous discussion on this issue.

**Comment by certik** [comment]
Thanks, I missed that. I'll copy my text above to that issue.
