### ISSUE TITLE
name="executable-name"  allows names with slashes

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#331]
Is it an intended feature for executable names to contains slashes?  Does not create a file outside of the package and works and could be useful for avoiding name conflicts but, particularly because you have to specify a source directory name in something like [[executable]]  I was assuming the name would have to be a simple base name; was testing how it worked with UTF-8 and checking for any ICE or what error messages would be produced from "incorrect" input and found it worked for the most part, but if that is not intended I think it should be checked for and flagged.

**Comment by LKedward** [comment]
With the label `"name"` I would say that this is not an intended feature in which case I agree that this should be checked somewhere.
