### ISSUE TITLE
Statically linked executables for releases (OSX)

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#356]
Is there anyway we can produce statically linked executables for the releases? Right now the Mac version requires gcc@9 to be installed.

**Comment by awvwgk** [comment]
Well, you can't link statically on OSX and I see no real way to circumvent this.

**Comment by awvwgk** [comment]
If homebrew provides `libgfortran.a` we might have a change to link at least statically against the GCC libraries, but if we only get dylibs there is not much of a chance here, unfortunately.

**Comment by everythingfunctional** [comment]
Well that's disappointing.

**Comment by awvwgk** [comment]
Yeah, it's a real pain to distribute (Fortran) software for OSX. My personal strategy is to avoid distributing software for OSX outside of package managers, *e.g.* conda-forge does a decent job to support both OSX x86_64 and aarch64 architectures.

**Comment by awvwgk** [comment]
WIth fpm now available on conda-forge for both OSX x86_64 and aarch64 we have some way to access binaries without requiring homebrew dependencies. For homebrew specific binary distributions we could either set up our own tap or submit to upstream homebrew and have them bottle fpm releases for us.

**Comment by awvwgk** [comment]
Let's continue this discussion in #400.
