### ISSUE TITLE
Run tests in specified order

### ISSUE THREAD

**Issue by ghost** [fortran-lang/fpm#375]
It took me a while to see the test itself is correct, but the commands are not being executed in specified order. I am using the master branch.

![fpm-test](https://user-images.githubusercontent.com/5913872/109647311-e4faee00-7b37-11eb-8be7-f820107f440f.png)

**Comment by sloorush** [comment]
Hi! this issue seems interesting to work on. Can someone please point me to what part of the codebase I should look to solve this issue?

**Comment by shreya024** [comment]
@LKedward I would like to work on this issue.Kindly assign

**Comment by Divyansh200102** [comment]
@LKedward is this issue still open?
