### ISSUE TITLE
Add a rationale to Readme.md

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/fpm#382]
Make has existed for decades, and many Fortran GitHub projects use CMake, which creates make files.  FPM may exist because of perceived deficiencies in make and CMake. I suggest that the Readme.md explain how FPM is intended to be better. I have trouble using CMake on Windows. I guess part of the rationale of FPM is to make the build process equally easy on all platforms.

**Comment by urbanjost** [comment]
`fpm` does do a very good job of building quite complex layouts of programs while largely masking the differences between different compilers (for straight-forward loads); but it also allows you to use external packages, which you would have to build your own rules with with make(1), for example. Even in the alpha stage if you showed a split screen showing how to set up a project using fpm(1) and Cmake(1) (let alone make(1)) I think `fpm` would look very appealing. The strongest case for make(1) is that it easily integrates with external packages in true "Unix toolkit" fashion; but new users in particular can be using Fortran via `fpm` long before they have read the man-pages for their compiler, learning how to build and load from libraries, and finding, pulling and building external packages and using make(1) don't you think?

**Comment by vmagnin** [comment]
Comparing with the powerful and complex CMake, fpm is user friendly like https://mesonbuild.com/

> Meson is an open source build system meant to be both extremely fast, and, even more importantly, as user friendly as possible.
The main design point of Meson is that every moment a developer spends writing or debugging build definitions is a second wasted. So is every second spent waiting for the build system to actually start compiling code.
