### ISSUE TITLE
Windows Command Prompt Can't Create Archives

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#384]
Running in a Windows Command Prompt, I get the error:

```
'ar' is not recognized as an internal or external command,
operable program or batch file.
```

which is not surprising, but I'm not sure what the correct command would be on Windows for creating archives for libraries.

**Comment by everythingfunctional** [comment]
According to [this stackoverflow](https://stackoverflow.com/questions/50848318/msvc-creating-a-static-library-via-makefile) answer, it is `link.exe -lib`.

**Comment by awvwgk** [comment]
It might also depend on the availability of MinGW or Cygwin type libraries. I would be interested in how compatible an archive created by `link.exe` is on a Cygwin Posix layer. For the setup we have on the GitHub Windows runner there is a wild mixture of MSYS2, git-bash and choco packages in the PATH, not sure which of them is providing the `ar` binary we are using to create the archive.

**Comment by arjenmarkus** [comment]
My first reaction was to write "they are incompatible", but a quick check
showed that the same file structure is used. I listed the contents of a
library file that was created with the Intel compiler on Windows using
Visual Studio, in a Cygwin command window, using ar. No problem.

That said, I am pretty sure that you cannot mix object files created by
compilers that have not been set up to be compatible with each other.

Op za 13 mrt. 2021 om 00:04 schreef Sebastian Ehlert <
***@***.***>:

**Comment by everythingfunctional** [comment]
Started looking into this a bit, and it appears msys/mingw do have `ar` available, but cmd and git Bash do not. Right now our set of os types only distinguishes between `OS_CYGWIN` and `OS_WINDOWS`. It seems we should have `OS_WINDOWS_CMD`, `OS_WINDOWS_GIT_BASH` and `OS_WINDOWS_MINGW`.

Unfortunately it seems we will be unlikely to distinguish based on environment variables alone (at least the ones we're currently checking).

Environment | OS | OSTYPE
---------------|----|---------
CMD | Windows_NT | N/A
git Bash | Windows_NT | msys
MinGW | Windows_NT | msys

Any thoughts on how to distinguish between git Bash and MinGW? Any thoughts on the names of the variables? Would `OS_CMD`, `OS_GIT_BASH` and `OS_MINGW` be sufficient or is that not explicit enough?

**Comment by arjenmarkus** [comment]
Plain MinGW-w64/MSYS2 command windows define an  environment variable
MSYSTEM: the values are MINGW32, MINGW64 and MSYS2 for the three flavours.

Git bbash seems to be based on MinGW-w64/MSYS2, so you cannot distinguish
it from plain MinGW.

Op do 18 mrt. 2021 om 17:09 schreef Brad Richardson <
***@***.***>:

**Comment by everythingfunctional** [comment]
My initial thought was that we would detect the environment and base our decision off that. But now I think we should just see if `ar` works, if so use it, if not try `link -lib`, and just fail if that one doesn't work. I'll try and see if we can tell from `execute_command_line` what works.
