### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#399]
I vaguely remember there being an fpm issue thread about this but now I can't find it.

fpm 0.1.3 and 0.1.4 have both had new features and/or changes. But only their bugfix version number was bumped up at release. If we follow semantic versioning, minor version number should have been bumped.

If we follow the current trend soon we will have 0.1.23, but 0.23.x may be more informative for the user.

Should we follow semver?

**Comment by LKedward** [comment]
Yes, I realised we had a change but I too couldn't find where we'd discussed the rules; for some reason I'd thought we had different rules for changes with a zero major version. Are you suggesting bump minor version for manifest/CLI changes while in alpha? This would make sense.

**Comment by milancurcic** [comment]
Yes, I suggest bump minor version for any changes (breaking or non-breaking) or additions during 0.x.x. Bump patch version for any fixes that don't add or change behavior. This is includes changes to docs.

Once at 1.x.x, bump minor version for non-breaking changes and additions, and major version for breaking changes.

I don't remember us deviating from semver rules, but I vaguely remember there were some questions or confusion about 0.x.x vs. 1.x.x.

**Comment by urbanjost** [comment]
I think it would be useful for everyone making a PR to put the #NNN  number at the end in the fpm.toml and internal version number as well.

**Comment by awvwgk** [comment]
Implemented now with the 0.2.0 release and going forward. Therefore, closing this as resolved.
