### ISSUE TITLE
Packaging: submit fpm to homebrew?

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#400]
What do you think, should we submit fpm to homebrew? This could to mitigate https://github.com/fortran-lang/fpm/issues/356.

Here is a working formula I created on Linuxbrew for testing:

```ruby
class Fpm < Formula
  desc "Fortran Package Manager (fpm)"
  homepage "https://fpm.fortran-lang.org"
  url "https://github.com/fortran-lang/fpm/releases/download/v0.1.4/fpm-0.1.4.f90"
  sha256 "06c139b16cf871e06cd3ea3be93c1ddbb5a94e4546a0c64822d10dc87333ac0c"
  license "MIT"

  depends_on "gcc" # for gfortran
  fails_with :gcc => "4"
  fails_with :gcc => "5"
  fails_with :gcc => "6"
  fails_with :clang

  def install
    # ENV.fc is not defined and setting it up with ENV.fortran will yield default gfortran
    ENV["FC"] = ENV.cc.gsub /gcc/, "gfortran"
    # Compile arguments need some tweaking
    system ENV["FC"], "fpm-0.1.4.f90", "-o", "fpm"
    bin.install "fpm"
  end

  test do
    system "#{bin}/fpm", "--version"
  end
end
```

Since I'm not a strong Linuxbrew user I won't have much use for fpm support in brew.

Documentation on submitting formulas to brew: https://docs.brew.sh/Formula-Cookbook

**Comment by ivan-pi** [comment]
I once tried using Linuxbrew but quickly reverted back to old habits. But I'm pretty sure that Homebrew is the best way to reach folks interested in scientific computing including Fortran on MacOS.

I know @zbeekman has made some contributions to Homebrew before.

**Comment by awvwgk** [comment]
I'm currently maintaining a homebrew tap for fpm at https://github.com/awvwgk/homebrew-fpm, if there is interest this could be migrated to the @fortran-lang namespace.

cc @certik @milancurcic @LKedward

**Comment by certik** [comment]
Last time I tried Homebrew, it installs things into `/usr/local`, which (I think) requires root, doesn't it? Either way, I don't think anything should write into `/usr`, neither on Linux, nor on macOS. The other problem with Homebrew is that it is macOS specific. For both of these reasons, I don't use it, and just use Conda on Linux, macOS and Windows. And I use `fpm` from there.

That being said, I think it's a good idea to submit to Homebrew and if @zbeekman would be willing to help, it should help expand our user base.

**Comment by awvwgk** [comment]
@certik It is quite a general question where we want to package fpm. I think generally we want to be in as many repositories as feasible. Meaning we have contributors that use the respective distribution and know how to package it.

Another question is whether this is an effort we want to centralize or keep distributed in the community.

**Comment by certik** [comment]
I agree, we should get `fpm` into as many package managers as possible. 

I would say we should try to get as involved as we can and our interests allow. Typically each package manager has its own way of accepting contributions, many are on GitHub, so we can just contribute as we see fit.

**Comment by rouson** [comment]
Given that the first comment in this issue contains a working Homebrew formula, what would be the downside in submitting it?  After not having tried homebrew on Linux in several years, I'm having good luck with it.  Getting into package managers does a lot to increase the chances of adoption.

**Comment by certik** [comment]
@rouson go ahead and submit it I would say.

**Comment by awvwgk** [comment]
Note that the formula above is outdated. I'm maintaining a tap for fpm at https://github.com/awvwgk/homebrew-fpm for my programming course. However, I didn't get it to build on Linuxbrew so far, due to the choice of GFortran default version.

There is no downside submitting it, but I'm not a brew user. Feel free to submit the formula if you like.

**Comment by awvwgk** [comment]
Homebrew does only accept stable software in homebrew-core (*e.g.* LFortran got rejected), therefore I don't think it makes send to submit fpm there. However, I can offer to migrate my tap to the @fortran-lang namespace if there is interest and we can maintain Fortran related packages collaboratively.

**Comment by rouson** [comment]
@awvwgk I'm interested in this and, as I mentioned above, I think it will do a lot to increase the likelihood of people adopting `fpm`.  Many novice users who are unfamiliar with building open-source software might not try a package that's not available via package manager.

**Comment by awvwgk** [comment]
Thanks, Damian. I'm looking for at least one user interested in maintaining this tap together with me. If you want I can add you as a collaborator to the repo.

**Comment by rouson** [comment]
@awvwgk I have no experience with maintaining a homebrew tap, but I'm now watching your tap's repository and will contribute however I am able.

**Comment by awvwgk** [comment]
I invited you as collaborator, for the tap setup I mostly followed this blog post: https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/.

**Comment by rouson** [comment]
@awvwgk thanks.  I just accepted the invitation.
