### ISSUE TITLE
Let's change the name of the default branch to "main"

### ISSUE THREAD

**Issue by rouson** [fortran-lang/fpm#421]
Please see https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/.

**Comment by milancurcic** [comment]
:+1: from me.

**Comment by awvwgk** [comment]
From a technical point of view an organisation owner of @fortran-lang can make the default branch rename at https://github.com/fortran-lang/fpm/settings/branches. Usually additional migrations are required:
- we have a workflow where the name of the default branch is hard coded
  https://github.com/fortran-lang/fpm/blob/d9dc9f2ae5f196c15a7d35cddabc805c40ff86ce/.github/workflows/docs.yml#L18
- we are referencing the default branch name in the fpm help page, documentation and contributing guide lines
- search below for master in this project, lot's of false positives, but some fpm related links are present:
```
❯ rg master .
./PACKAGING.md
649:`helloff = { git = "https://gitlab.com/everythingfunctional/helloff.git", branch = "master" }`,

./CONTRIBUTING.md
12:[fpm license](https://github.com/fortran-lang/fpm/blob/master/LICENSE).
24:[Fortran stdlib style guide](https://github.com/fortran-lang/stdlib/blob/master/STYLE_GUIDE.md)
38:   Try to reproduce it with the latest version from the master branch.
112:  [Fortran stdlib style guide](https://github.com/fortran-lang/stdlib/blob/master/STYLE_GUIDE.md).

./docs.md
5:project_download: https://github.com/fortran-lang/fpm/archive/master.zip

./src/fpm_command_line.f90
715:    '   https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md        ', &

./src/fpm/cmd/new.f90
136:        &'  #     https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md   ',&
138:        &'  #     https://github.com/fortran-lang/fpm/blob/master/PACKAGING.md            ',&
350:        &'  # like. By default the latest master master branch is used. You can           ',&
357:        &'#stdlib = {git="https://github.com/LKedward/stdlib-fpm.git",branch = "master" },',&

./manifest-reference.md
406:toml-f = { git = "https://github.com/toml-f/toml-f", branch = "master" }
```

**Comment by awvwgk** [comment]
I'm all for migrating the default branch name, but I don't think it makes much sense unless it happens for all @fortran-lang repositories. Beside fpm those repositories are currently using master as name for the default branch

- https://github.com/fortran-lang/stdlib
- https://github.com/fortran-lang/stdlib-docs
- https://github.com/fortran-lang/fpm-haskell
- https://github.com/fortran-lang/fpm-registry
- https://github.com/fortran-lang/fortran-lang.org
- https://github.com/fortran-lang/talks
- https://github.com/fortran-lang/benchmarks

**Comment by milancurcic** [comment]
> I'm all for migrating the default branch name, but I don't think it makes much sense unless it happens for all @fortran-lang repositories.

We should do it for all repos but it doesn't need to happen all at once.

For the transition, instead of renaming "master" -> "main" in the settings, do you think this flow would work:

1. Create a branch "main" from "master"
2. Do necessary PRs for docs and CI to work with "main"
3. Change default branch in settings from "master" to "main"
4. Delete "master" branch.

**Comment by rouson** [comment]
@milancurcic the workflow you outlined is what I've done on other repositories where I've made this change.

**Comment by awvwgk** [comment]
> For the transition, instead of renaming "master" -> "main" in the settings, do you think this flow would work:
> 
>   1. Create a branch "main" from "master"
>   2. Do necessary PRs for docs and CI to work with "main"
>   3. Change default branch in settings from "master" to "main"
>   4. Delete "master" branch.

It seems that GitHub is offering a somewhat more seamless way of renaming branches, which will automatically create a redirect from "master" to the new branch name. This only leaves step 2 as a follow-up to the renaming, everything else will be automatic.

I'm happy to start with doing the necessary changes for fpm and we can evaluate how this strategy works out in practice before taking on the other repositories.

**Comment by jvdp1** [comment]
fine for me!

**Comment by milancurcic** [comment]
@awvwgk Wonderful, I didn't know about it. Sounds like the way to go.

**Comment by awvwgk** [comment]
Just did the renaming, let me know if it works as expected.

**Comment by awvwgk** [comment]
Here is what I did to update my local git repository (I'm using `github` as identifier for *this* repo, `upstream` is my fork):

```
❯ git checkout master
Switched to branch 'master'
Your branch is up to date with 'github/master'.
❯ git branch -m master main
❯ git fetch --all --prune
Fetching upstream
From github.com:awvwgk/fortran-package-manager
 - [deleted]           (none)     -> upstream/master
   (refs/remotes/upstream/HEAD has become dangling)
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13 (delta 6), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (13/13), 3.37 KiB | 313.00 KiB/s, done.
 * [new branch]        main       -> upstream/main
Fetching github
From github.com:fortran-lang/fpm
 - [deleted]           (none)     -> github/master
remote: Enumerating objects: 690, done.
remote: Counting objects: 100% (690/690), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 484 (delta 464), reused 482 (delta 462), pack-reused 0
Receiving objects: 100% (484/484), 82.67 KiB | 1.02 MiB/s, done.
Resolving deltas: 100% (464/464), completed with 197 local objects.
   86ec00b6..0a9d845e  gh-pages   -> github/gh-pages
 * [new branch]        main       -> github/main
❯ git branch --set-upstream-to github/main
Branch 'main' set up to track remote branch 'main' from 'github'.
```
