### ISSUE TITLE
Changing link entry doesn't trigger relinking targets

### ISSUE THREAD

**Issue by brocolis** [fortran-lang/fpm#422]
Consider this section in _fpm.toml_
```
[build]
link = ["lapack", "blas"]
```
I can run `fpm build`, etc. When I change the section to
```
[build]
link = ["lapack", "openblas"]
```

then `fpm build` doesn't link the project using the new settings (nothing happens).

**Comment by LKedward** [comment]
Hi @brocolis, can you try without lapack, just openblas on its own? I don't think you need both lapack and openblas together.

**Comment by brocolis** [comment]
Hi @LKedward, it doesn't work either. I also tried ```link = ["nonexistent", "nonono"]``` , nothing happens.

![link](https://user-images.githubusercontent.com/5913872/113341090-1e737480-9303-11eb-9e70-53ab319438d1.png)

It looks like I have to delete the _build_ subdirectory and build everything from the start.

**Comment by awvwgk** [comment]
I think the issue is that the manifest is currently not hashed, but probably should be. We could either hash the complete the fpm.toml and always rebuild on any change (lot's of unnecessary rebuiilds) or hash relevant sections like `build.link` or the `link` entry in the targets and have the link step depend on this change.

**Comment by LKedward** [comment]
Ah yes of course. Agreed, we should hash the relevant sections of the manifest.

**Comment by awvwgk** [comment]
A good mechanism for this would be to use a different output directory for the executables which additionally depends on the link arguments and not only on the compile arguments.

I talked with Jakub @kubajj about this in the context of the compiler profiles, the different build directories implemented there would provide the required mechanism to resolve this and would also provide a way to get the first part of the compiler profiles into fpm.

**Comment by kubajj** [comment]
So if I understood correctly, do we need to add the hash of `build.link` into the build name directory of the executable that depends on the link target?
