### ISSUE TITLE
Command line is too long

### ISSUE THREAD

**Issue by brocolis** [fortran-lang/fpm#427]
Steps to reproduce

```batch
fpm new tmp
cd tmp
```

Add to `fpm.toml`:

```toml
[dependencies]
blas = {git = "https://github.com/brocolis/blas" }
```

Back to terminal,

```batch
fpm build
```

After some time, I got an error
```
+ ar -rs build\gfortran_2A42023B310FA28D\tmp\libtmp.a build\gfortran_2A42023B310FA28D\tmp\src_tmp.f90.o … 

Command line is too long
 Command failed
ERROR STOP
```

**Comment by awvwgk** [comment]
I have seen issues regarding this in the [ninja build system](https://github.com/ninja-build/ninja), this is a known issue on Windows. Their solution is to rely on response files to pass the command line rather than actual command line arguments for this reason.
