### ISSUE TITLE
Revisit extra table in package manifest

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#430]
This might be helpful for plugins that want to store their configuration in the package manifest while avoiding to clash with any actual fpm reserved keywords. All fpm has to do is ignore any entries in a special table (maybe named *extra(s)*, *plugin(s)*, ...).

See https://github.com/fortran-lang/fpm/pull/232 for the original proposal.

**Comment by certik** [comment]
As suggested here: https://fortran-lang.discourse.group/t/joining-the-team/1626/6, we could use this to specify formatting options like:
```toml
[extra.lfortran.fmt]
indent = 3
```
That makes sense, to have all such project specific options in `fpm.toml` and we can teach `fpm` about formatting via LFortran (and/or other tools).

**Comment by awvwgk** [comment]
I opened [lfortran!487](https://gitlab.com/lfortran/lfortran/-/issues/487).
