### ISSUE TITLE
toml or yaml or something else

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#44]
Are we sold on using toml as the file format for a package manifest/configuration file?

I see that Rust uses toml, but many other package mangers use others. Haskell's Stack uses yaml, and I think I've seen others use that. I think I've also seen json, and maybe even xml.

A new project Cargo.toml looks like:

```
[package]
name = "rusttest"
version = "0.1.0"
authors = ["Brad Richardson <brichardson@structint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

and a new project package.yaml (for Haskell) looks like:

```
name:                haskelltest
version:             0.1.0.0
github:              "githubuser/haskelltest"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskelltest#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskelltest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskelltest

tests:
  haskelltest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskelltest
```

I'm not strongly opposed to toml, but it's the one I'm least familiar with. My gut tells me we should go with yaml. I would not suggest json or xml though, too much syntax/line noise.

**Comment by milancurcic** [comment]
Both toml and yaml look good and have sufficient capability. Yaml is personally slightly prettier to me.

Which has a more mature parser in Haskell? Let's go with that one.

I recommend against json for configuration files (even though I use it a lot) because it doesn't allow comments. This would make it harder to work with them in development and testing when you want to quickly try out different values. It's also a bit more noisy (verbose) than either toml or yaml. 

xml burns my eyes.

**Comment by everythingfunctional** [comment]
There are parsers for both that seem pretty mature. I just think yaml is more naturally represented as a simple/common data structure, so it is easier to work with once it's parsed.

@certik , do you have a vote?

**Comment by certik** [comment]
I vote for toml, I think it's more readable, that's what Rust and Python uses and I would follow exactly the Rust model for everything unless we have a good reason not to. Fortran is close to Python and Rust in most respects than to Haskell.

**Comment by certik** [comment]
Here are good pros and cons:

https://www.reddit.com/r/rust/comments/7izxrg/toml_or_yaml_for_config/

One big downside of yaml is that it is very complicated. TOML is very simple for flat configuration files, and Cargo shows that flat is enough. And we should strive for flat.

I agree that we should not use JSON or XML.

**Comment by everythingfunctional** [comment]
@certik , that sounds reasonable. I put together an example of what an `fpm.yaml` file would look like (#46). Could you try converting that to toml so we can see what that would look like?

**Comment by milancurcic** [comment]
I am now in favor of toml as well.

**Comment by certik** [comment]
@everythingfunctional see my comments at #46: https://github.com/fortran-lang/fpm/pull/46#issuecomment-598532895 how it would look like in YAML and TOML. Let me know your thoughts.

**Comment by everythingfunctional** [comment]
I think the TOML looks fine. I'll start trying to put together the logic to pull in the dependencies, and compile them in the right order based on the `fpm.toml` file.

**Comment by certik** [comment]
@everythingfunctional perfect. Let me know once you have something, and I'll test it.

**Comment by everythingfunctional** [comment]
I'm going to go ahead and close this issue, since I think we've decided to stick with toml. Plus we're now moving forward in that direction.
