### ISSUE TITLE
Package File Spec

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#45]
We need a specification, or at least a start of one, for what should go into the package file and how it should be organized.

I'd suggest we start by answering the question "What does fpm need to know about a package in order to be able to build it?" in as much detail as possible and then trying to organize it logically.

**Comment by everythingfunctional** [comment]
I think we've settled this now?

**Comment by certik** [comment]
Yes.

**Comment by everythingfunctional** [comment]
Ok, closing.
