### ISSUE TITLE
Option to unconditionally rebuild projects

### ISSUE THREAD

**Issue by ghost** [fortran-lang/fpm#454]
It would be nice to have an option to unconditionally rebuild projects - akin to GNU make' `-B|--always-make` [1]

As an example, consider this use case
```batch
fpm build
set PATH=C:\gfortran-11-RC1\bin
fpm build -B
set PATH=C:\gfortran-9\bin
fpm build -B
```

Alternatively, @urbanjost suggested "clean" subcommand in https://github.com/fortran-lang/fpm/issues/127

I also like this syntax:

```batch
fpm build
set PATH=C:\gfortran-11-RC1\bin
fpm clean build
set PATH=C:\gfortran-9\bin
fpm clean build
```

[1] https://www.gnu.org/software/make/manual/html_node/Options-Summary.html

**Comment by brocolis** [comment]
A `fpm-clean` plugin would work for now.
