### ISSUE TITLE
fpm displays GNU' ar Copyright notice 

### ISSUE THREAD

**Issue by brocolis** [fortran-lang/fpm#456]
fpm git~master started displaying GNU' ar Copyright notice on build, run and install subcommands.

Example output:

```
C:\Temp>fpm new test222
 + mkdir test222
 + cd test222
 + mkdir test222\src
 + mkdir test222\app
 + mkdir test222\test
 + git init test222
Initialized empty Git repository in C:/Temp/test222/.git/

C:\Temp>cd test222

C:\Temp\test222>fpm build
 + mkdir build\dependencies
GNU ar (GNU Binutils) 2.35.2
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
 + mkdir build\gfortran_2A42023B310FA28D\test222  … 

C:\Temp\test222>fpm run
GNU ar (GNU Binutils) 2.35.2
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
 Hello, test222!
```

**Comment by LKedward** [comment]
Thanks for reporting; that's a little annoying. Looks like this execute command line needs to be piped to `/dev/null` and the Windows equivalent.

https://github.com/fortran-lang/fpm/blob/a9adf2b3ed09d0769f1095ddf7c2c06f71f10161/src/fpm_environment.f90#L196

**Comment by brocolis** [comment]
I think the archiver resolution should be part of a more general toolchain profile. For example, if the compiler is `gfortran`, then `fpm` can assume the archiver is `ar`, the assembler is `as`, the C++ compiler is `g++`, etc.

**Comment by isuruf** [comment]
> For example, if the compiler is gfortran, then fpm can assume the archiver is ar, the assembler is as, the C++ compiler is g++, etc.

fpm should first look at AR env variable and if not set ask gfortran what the archiver name is `gfortran -print-prog-name=ar` should give the archiver name.

cc @certik
