### ISSUE TITLE
Add an option to run fpm in a subdirectory

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#481]
Currently `fpm` must be run from the root directory where `fpm.toml` is. We should extend the usage to also work in any subdirectory of the project. Just like `git` works. That way you can go into into a subdirectory, use `vim` to edit a file and do `fpm build` or `fpm test` to run tests right away. Currently you have to have two terminals open, one where you run `fpm build` and another way where you can go into subdirectories to edit files.

Related issues: #411, #410.

**Comment by awvwgk** [comment]
As a `vim` user I have to strongly disagree on the above issue, so far it never occurred to me to leave the project root directory to edit a file.

Joke aside, a `-C` like option would be a welcome addition. I would prefer we find a way to implement it without explicitly carrying around the current working directory in the fpm source and pass it along to shell processes spawned by `execute_command_line`, maybe there is a simple solution to change the working directory for the process using `stdlib_os`.

**Comment by LKedward** [comment]
Duplicate of #172. See there for some brief discussion of using chdir for this.

**Comment by certik** [comment]
Closing in favor of #172.

**Comment by certik** [comment]
> As a `vim` user I have to strongly disagree on the above issue, so far it never occurred to me to leave the project root directory to edit a file.

Can you be more specific what you strongly disagree with? What I described is a very common workflow situation, as for example described in #172.

**Comment by awvwgk** [comment]
Just a curiosity I noticed, many people use `cd src; vim fpm.f90` rather than just using `vim src/fpm.f90`. The latter will retain the working directory as the project toplevel and allow to easily run commands with `:!fpm run` from inside vim, together with the `netrw` built-in file navigator (`:E`) I usually tend to open a single `vim` session while working on a project without ever changing directories. It's quite liberating to know you can always run any command straight from vim in the project root.

**Comment by certik** [comment]
I see. Yes, I used to use `:!...` a lot. I even have this in my `.vimrc`:
```vim
map <F10> :!/usr/bin/env python %<CR>
```
To run the currently opened file. But being in the current directory and `:!fpm run` should now work also due to #483. I also frequently escape `vim` and do `git diff .` to see the changes just in this directory, `ls`, etc.
