### ISSUE TITLE
Support appending flags

### ISSUE THREAD

**Issue by isuruf** [fortran-lang/fpm#482]
In other build systems, a user can give a set of flags that are appended to the default set of flags.
`fpm build --flag <flags>` overrides the defaults which is not what I want.

Also, it'd be great if this was supported as an environment flag `FFLAGS` which would make fpm
behave like every other build system. (CMake, autoconf, setuptools, meson, etc)

**Comment by awvwgk** [comment]
To retain the defaults you can specify the profile you want to append your flags to
```
fpm build --profile release --flag <flag>
```

Reading from `FFLAGS` automatically would be nice, but we are also ignoring `FC` right now and use our own `FPM_COMPILER` variable instead.

**Comment by isuruf** [comment]
Thanks @awvwgk. If I have a set of flags in `FFLAGS`, I can't pass them like `fpm build --profile release --flag $FFLAGS ` right? Is there a way to send in multiple without specifying `--flag` multiple times?

**Comment by awvwgk** [comment]
I don't see why
```
fpm build --profile release --flag "$FFLAGS"
```
wouldn't work for this purpose.

**Comment by awvwgk** [comment]
We are actually using this already for bootstrapping:
https://github.com/fortran-lang/fpm/blob/6d9004d93460dc15b99051c90d1b58d724b010e6/install.sh#L69

**Comment by isuruf** [comment]
That's great. Thanks.
