### ISSUE TITLE
Don't Print Backtrace When Unit Tests Failed

### ISSUE THREAD

**Issue by Carltoffel** [fortran-lang/fpm#485]
If one test in the testing framework called by `fpm test` fails, the framework will likely return an exit code `>0`. This leads to `fpm` calling `error stop` which causes printing the backtrace in the console (at least if `fpm` was compiled with gfortran). This can cause some confusion, because the program did exactly what it was meant to do, but the backtrace implies something went unexpectedly wrong.

@everythingfunctional and I discussed the same behaviour in his [vegetables project](https://gitlab.com/everythingfunctional/vegetables/-/issues/24) where he ended up with replacing `error stop` with `stop 1`. Brad tested some combinations of compiler and OS and it sounds promising as long as there aren't multiply images.

What do you think? Does the same approach applies for `fpm` or is there even a better way?

**Comment by LKedward** [comment]
Yes I agree, we don't need to be using `error stop` in fpm. I started [work]https://github.com/LKedward/fpm/commit/086ae55dfa09c1924d2b54bc88ddb1827f9dcfa7) on improving the error handling messages during compilation which would extend naturally to the case described here.
