### ISSUE TITLE
Erroneous error message

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#488]
I am trying to convert an existing project to using fpm. Unfortunately (or maybe not), fpm complains about an invalid module name for something that is not defining a module. Granted this is not the kind of code I'd ever expect to actually encounter, but it is something to consider. The specific error message is:

```
Parse error: empty or invalid name for module
././src/pfm/distributions_m.f90:52:12
   |     module real*8 function get_log_logistic_p(x,a,b,c)
   |            ^
```

This is at an intermediate step in converting some legacy code, so that `real*8` will get removed, but this is a general situation that could arise that the parser needs to handle. The idea is that for `module <other_stuff> function | subroutine`, this isn't defining a module, so just skip it.

**Comment by LKedward** [comment]
Thanks for reporting - I'll look at putting together a fix for this case. I'm hoping to push some improvements to the source parsing module in the future to improve robustness and maintainability.

**Comment by everythingfunctional** [comment]
Just as additional info, I also got a duplicate module error on the same project due to declarations like `module double precision function` after fixing that issue. It would be nice if that error message included the name of the module it thinks is a duplicate, as that one took me a bit to work out.

**Comment by LKedward** [comment]
@everythingfunctional, are you sure it didn't print the names of the duplicate modules?.
The code linked below should print the duplicates:

https://github.com/fortran-lang/fpm/blob/87a2cbfda5ac064c754e493d41950fde72e05fc7/src/fpm.f90#L233-L234

**Comment by everythingfunctional** [comment]
@LKedward I think maybe I just missed it. I just tried to reproduce it and got this:

```
Warning: Module double in ././src/pfm/radiation_shift_m.f90 is a duplicate
```

So maybe I just didn't realize that `double` was the name of the module it thought it found. Maybe we should put quotes around the module name to make it clearer?
