### ISSUE TITLE
Can't pass flags containing an equals sign(=) with multiple executables

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fpm#495]
I was trying to pass the `-fsanitize=address` flag to gfortran, but fpm/M_CLI2 is treating `address` as an unnamed parameter.

**To reproduce:**
```sh
$ fpm new test && cd test
$ cp app/main.f90 app/main2.f90
$ fpm run --flag "-fsanitize=address"
```

**Output:**
```sh
 + mkdir -p build/dependencies
fpm::run<ERROR> specified names "address" not found.

 Available names:
main2  test
STOP 1

```

**Comment by urbanjost** [comment]
Doing some further testing but will put in a pull request to use a more recent version of M_CLI2. Trying to decide what all needs added to test suite too.  

```text
[dependencies.M_CLI2]
git = "https://github.com/urbanjost/M_CLI2.git"
rev = "143ab3a4b4f82810f2dda2333cb5a0f116b955e5"
```
