### ISSUE TITLE
Fpm fails to create a new project in Windows

### ISSUE THREAD

**Issue by RecruitMain707** [fortran-lang/fpm#496]
I downloaded the latest precompiled binary, running `fpm --help` works, but i cannot create a new project.

running this: `fpm new fpm-test`

outputs this:
```
The system could not find the specified route.
The system could not find the specified route.
The system could not find the specified route.
The system could not find the specified route.
The system could not find the specified route.
 + mkdir test-fpm
 execute_command_line() failed
ERROR STOP

Error termination. Backtrace:

Could not print backtrace: libbacktrace could not find executable to open
#0  0xffffffff
#1  0xffffffff
#2  0xffffffff
#3  0xffffffff
#4  0xffffffff
#5  0xffffffff
#6  0xffffffff
#7  0xffffffff
#8  0xffffffff
#9  0xffffffff
#10  0xffffffff
```

Building a manually created project doesnt work either, so i guess its a problem related to running commands.

**Comment by LKedward** [comment]
Thanks for reporting @RecruitMain707. May I ask whether the same message appears when you run other commands in Windows command prompt such as `dir` or `cd`?

**Comment by RecruitMain707** [comment]
No, it only appears when i try to use fpm commands

**Comment by brocolis** [comment]
Hi @RecruitMain707, which `fpm` binary are you using? This one https://github.com/fortran-lang/fpm/releases/download/v0.2.0/fpm-0.2.0-windows-x86_64.exe works for me in Windows 10 x64.

**Comment by RecruitMain707** [comment]
Hello, i am using the latest release, yes, am i missing some requisite perhaps?

**Comment by LKedward** [comment]
> am i missing some requisite perhaps?

The release binaries are self-contained and hence you shouldn't need to download/install any other prerequisites.

Can you tell us what the output is when you run the following commands from command prompt:
```batch
REG QUERY "HKLM\Software\Microsoft\Command Processor"
REG QUERY "HKCU\Software\Microsoft\Command Processor"
```

**Comment by RecruitMain707** [comment]
sure:
```cmd
> REG QUERY "HKLM\Software\Microsoft\Command Processor"

HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor
    DefaultColor    REG_DWORD    0x0
    EnableExtensions    REG_DWORD    0x1
    CompletionChar    REG_DWORD    0x40
    PathCompletionChar    REG_DWORD    0x40
```
```cmd
> REG QUERY "HKCU\Software\Microsoft\Command Processor"

HKEY_CURRENT_USER\Software\Microsoft\Command Processor
    Autorun    REG_EXPAND_SZ    "C:\ProgramData\Anaconda3\condabin\conda_hook.bat"
    CompletionChar    REG_DWORD    0x9
    DefaultColor    REG_DWORD    0x0
    EnableExtensions    REG_DWORD    0x1
    PathCompletionChar    REG_DWORD    0x9
```

**Comment by LKedward** [comment]
Thanks - I think you have an old or outdated autorun script (`C:\ProgramData\Anaconda3\condabin\conda_hook.bat`) running every time command prompt starts. I'm not sure what the recommended procedure is for fixing a Conda installation - perhaps `conda init --reverse` and/or `conda init`?

**Comment by LKedward** [comment]
Hi @RecruitMain707, can you try running the following commands:

```cmd
REG DELETE "HKCU\Software\Microsoft\Command Processor" /v Autorun
conda init
```

and then try fpm again?

**Comment by RecruitMain707** [comment]
Sorry for the long wait, i uninstalled conda a while back, so i only had to remove it, it now works perfectly, thank you so much.
