### ISSUE TITLE
Naming of `fpm.toml`

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#5]
Naming of `fpm.toml`. Cargo names `Cargo.toml` with capital `C`, and as explained in https://doc.rust-lang.org/cargo/faq.html#why-cargotoml, to "*ensure that the manifest was grouped with other similar configuration files in directory listings. Sorting files often puts capital letters before lowercase letters, ensuring files like `Makefile` and `Cargo.toml` are placed together.*" If we want to do the same, the candidates are `Fpm.toml` and `FPM.toml`. I think `fpm.toml` looks better. But using a capital letter would make it similar to `CMakeLists.txt` also. We might want to devise a different name or naming scheme. Any ideas?

**Comment by milancurcic** [comment]
If we consider `fpm.toml`, I like it better than either `Fpm.toml` or `FPM.toml`. I see little value in the sorting argument.

If I think of any better names than `fpm.toml`, I will write here, but I think `fpm.toml` is just fine.

**Comment by ivan-pi** [comment]
If I get it correctly in the Rust world libraries/packages are called *crates*, and the package manager called *Cargo* is responsible for shipping these crates? 

In line with the Rust naming, if you don't mind playing with some old Fortran terminology, crates would become *decks* (as in punched card decks), and the Fortran package manager would be a *box/package/drawer/folder/cabinet/chest/case/dealer/dispenser/pile/loader/...?...*. Unfortunately none of these words really ring. The  `fpm.toml` acronym is also easy enough to remember.

From Wikipedia:
> ...a box of computer programs in punched card form from the early 1970s. The deck in the middle shows what a program deck looked like after extensive editing and debugging. The cardboard box was originally used to ship blank cards and held 2000 cards.

![image](https://user-images.githubusercontent.com/21085643/72416874-efadc480-3777-11ea-9f81-2d0f6dfaf22e.png)

**Comment by certik** [comment]
Thanks @ivan-pi for the ideas.

I *think* a Rust package is simply called a *crate*, but even I am not 100% sure. For that reason I would recommend to simply call a package as a *package*, so that people know what that means.

I agree, let's just use `fpm.toml`.

**Comment by everythingfunctional** [comment]
Should we close this now? We've implemented it as `fpm.toml`.

**Comment by certik** [comment]
Yes, can be closed.

**Comment by everythingfunctional** [comment]
Ok, closing.
