### ISSUE TITLE
building fpm with ifort

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#520]
Is there any interest in a version of fpm that can be built with the Intel ifort compiler?  There is what I think is a bug in ifort that can be worked around, as demonstrated by the single-file build in
 https://github.com/urbanjost/fpm-tools/blob/main/tools/bootstrap/fpm_intel.F90
but it we just want to stick with gfortran for building fpm itself I don't want to make the kludge (essentially, changing the USE FPM_TOML to a USE TOMLF for TOML_TABLE). If you want to see the error, look for the lines with !x! and switch which module TOML_TABLE is used from).

Other than it being useful during development of fpm to use multiple compilers and their associated tools (not a trivial advantage by itself) does anyone have a use-case like an environment where everything must be built from source and a recent gfortran(1) is not installed?  That is, is anyone being held back from using fpm(1) that would be able to use it if it built with ifort(1)?

**Comment by arjenmarkus** [comment]
On Windows, gfortran is not always easy to install - not impossible, but
there is a wealth of possibilities, whereas people may be more used to
environments like MS Visual Studio that hide the details of the build
process.

Op do 15 jul. 2021 om 15:37 schreef urbanjost ***@***.***>:

**Comment by arjenmarkus** [comment]
I compiled the current version with Intel oneAPI and that worked fine. I
have not tested it to any useful extent, but at least the first step was
done.

Op do 15 jul. 2021 om 15:53 schreef Arjen Markus ***@***.***
