### ISSUE TITLE
stack build does not add fpm executable to path

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#55]
First time running stack. On running `stack build`, it looks like the fpm executable is not installed in any working path. I expected it to be installed either somewhere under stack like pip does, or locally and then added to my path.

For example, I'm working in /home/milan/Work/fortran/fpm, fpm-exe is installed here: /home/milan/Work/fortran/fpm/.stack-work/install/x86_64-linux-tinfo6/68e6a00e61079ec9146947ae047a1ce619d26ace12c1e4cd5fd58ceb496743b0/8.6.5/bin

so I had to add this to my `PATH`. 

Is this expected behavior? If not, is this an issue with stack or with fpm?

fpm-exe should be called just fpm.

**Comment by everythingfunctional** [comment]
`stack build` is not supposed to install the executable. I'll have to try it, but I believe `stack install` will do what you are after. I think it typically will install it to `$HOME/.local/bin`.

**Comment by milancurcic** [comment]
Thanks, I tested `stack install` and it works.
