### ISSUE TITLE
Clicking the green "New issue" button doesn't start a new issue

### ISSUE THREAD

**Issue by rouson** [fortran-lang/fpm#555]
See the attached screen shot.  Is this intentional?    I at first didn't notice the "Open a blank issue" link so the page that comes up after clicking "New issue" is a little confusing.

![Screen Shot 2021-09-02 at 9 46 40 AM](https://user-images.githubusercontent.com/13108868/131884275-beb422a8-f681-4dd7-be1a-646cbd547a89.png)

**Comment by milancurcic** [comment]
I think this is expected. If I recall correctly @awvwgk made this so that users asking for help with using fpm would not open issues in the GitHub repo. If we choose to continue with this flow, we should also link to the GItHub Discussions.

**Comment by awvwgk** [comment]
We can add issue templates as well and customize the list. Will send a patch for this soon(ish).

**Comment by awvwgk** [comment]
Can you checkout this setup:
https://github.com/awvwgk/fortran-package-manager/issues/new/choose
