### ISSUE TITLE
Adding source tarballs to the release

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#559]
We are currently using the automatically generated source tarballs/archives by the git-archive command. In the past those have caused issues due to changes in the git-archive command which changed the checksum of the generated tarballs and therefore broke several packaging workflows relying on git-archive generated tarballs.

An option would be to create an additional workflow to upload source tarballs in the release CI together with a checksum. What would be the best format here? Is everybody fine with `tar.xz` or `tar.zst` or should we use `zip`?

Some package ecosystems have this as soft requirement (I was recently asked to add source tarballs to my releases to contribute a package to spack).

**Comment by urbanjost** [comment]
If it has to be just one, ZIP is usually the answer not because it is best, but because it is freely available and standard on MSWindows and easily available if not installed by default on GNU/Linux, Linux, ...  I generally try to provide at least two; a ZIP and a TGZ file even though there are other great ones out there.

**Comment by awvwgk** [comment]
Multiple might become quite redundant in terms of build artifacts, but if there is really need we can have multiple source archives. I'll go with zip for now.

**Comment by awvwgk** [comment]
For future reference, generating a couple of archives for all released tags:
```bash
format=zip
for version in $(git tag | tr -d '[:alpha:]'); do
  git archive --prefix fpm-$version --format $format v$version > fpm-$version.$format
  sha256sum fpm-$version.$format > fpm-$version.$format.sha256
done
