### ISSUE TITLE
Creating Windows installer for fpm

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#580]
### Description

Since Windows has no actual package manager installing of software is usually expected to be possible by an installer. So far fpm does not explore this road for distribution, we are using binary releases and MinGW packages for pacman instead.

### Possible Solution

Find out how we can automatically create an installer using GitHub actions

### Additional Information

- https://nsis.sourceforge.io/Main_Page
- NuGet packages?

**Comment by awvwgk** [comment]
Just saw Laurence @LKedward has created an installer for fpm: https://github.com/LKedward/quickstart-fortran

**Comment by LKedward** [comment]
Yes I had a play around with NSIS as a weekend project and came up with this. I ended up bundling in GFortran, Git and OpenBLAS as well to make an all-in-one installer aimed at beginners. I will share on the Discourse to get feedback - if people find it works well, we could move under Fortran-Lang namespace and link to it from the website perhaps?

The same workflow can be adapted to create an *fpm*+Git for Windows installer in this repository for each release.
