### ISSUE TITLE
Not picking up some environment variables

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#583]
### Description

Was trying some of the options with environment variables and it is not working with some of them, and I believe that if GET_FPM_ENV was concatenating FPM_PREFIX and ENV instead of FPM_PREFIX and VAL that the problem would be resolved. That is, "fpm_prefix//val"  should be "fpm_prefix//env".

```fortran

 !> Get an environment variable for fpm, this routine ensures that every  variable    
 !> used by fpm is prefixed with FPM_.
    function get_fpm_env(env, default) result(val)
      character(len=*), intent(in) :: env
      character(len=*), intent(in) :: default
      character(len=:), allocatable :: val
      character(len=*), parameter :: fpm_prefix = "FPM_"
      val = get_env(fpm_prefix//val, default)
    end function get_fpm_env
end module fpm_command_line
```

### Expected Behaviour

I expect that when variables like FPM_FC are set they become the default compiler.

### Version of fpm

0.4.0

### Platform and Architecture

All

**Comment by awvwgk** [comment]
Good catch, thanks.

**Comment by urbanjost** [comment]
No problem. You fixed it so fast I thought I hadn't hit the save button earlier and was going to reenter it!
