### ISSUE TITLE
Start dedicated user documentation site

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fpm#599]
See <https://github.com/fortran-lang/fpm/pull/598#issuecomment-956134712>.

There are lots of options available for generating nice documentation sites.
One requirement will be to support multiple versions for each release of *fpm*.
Also will we store the docs in the same repo here or in a separate one?

**Comment by zoziha** [comment]
I have used `mdbook` (see [GitHub repo](https://github.com/rust-lang/mdBook) and [its Doc website](https://rust-lang.github.io/mdBook/)), it uses `book.toml` to configure `markdown` documents, we will feel familiar. (`mdbook` is a potential option)

> mdBook is a utility to create modern online books from Markdown files.

**Comment by awvwgk** [comment]
Sphinx+MyST would also be a good option. It can be maintained in a separate subdirectory here and deployed automatically via GitHub actions to fpm.fortran-lang.org.

**Comment by urbanjost** [comment]
The help text of fpm was originally written with the idea of running it through txt2man; and then using man(1) convert to HTML or dvi and so on, which (with a little editing) produces 

file:///home/urbanjs/venus/V600/github/fpm-tools/docs/manual.html

as well as man-page files for ULS (*nix) systems. I looked for a man-to-markdown utility utility. Alternatively I was looking for a markdown-to-text converter so the help could alternatively be written as markdown but produce ASCII text that could be included into fpm that was simple enough to be written in Fortran but could not find one. So one alternative might be to write the help as markdown, and then have a tool that would convert it into flat text which could easily be converted to INCLUDE files? There are so many variants of markdown that seems problematic; but anything that converts are available for converting to text could be used (HTML, LaTeX, ....) although that would be build dependency for the maintainers, it could perhaps be done via CI/CD when doing a PR.

**Comment by urbanjost** [comment]
Even a brute-force script
using groff demonstrates the possible process of automatically generating
a HTML representation of the help text with each PR from a CD/CI script.

groff(1) does not produce particularly great results and the CSS style
sheet could definitely be improved. This is just for demonstration
purposes, but I think something like this could be used to make on-line
documenation available via the fpm webstite. Not quite sure how to place
the results back onto the web page as I have not used an artifact file
yet, but even if another approach is taken such as mentioned above,
as long as "fpm help manual" produces a man-page-like output this would
continue to work.

So just to keep it simple (the CSS style would be inserted correctly using
something like sed(1), and would have to experiment with whether man2html,
pandoc, etc. is best in a CD/CI environment) but does the general concept
seem like something to go forward with? If so, any suggestions?

Anyone used man2html(1) in a CD/CI environment?

Would individual documents be better than a single document?

Should actual man-pages be generated as well?

The one listed above produces better results using a slightly modified man2html,
but if anyone has a better CSS page using groff(1) would probably be the easiest
to maintain.

I keep meaning to make a Fortran version of txt2man(1) using a RE library but
never get around to it, as txt2man(1) works for what I need; but that would be
an interesting method to create

A quick bash shell script only using groff(1) (probably in the default environment?)
and curl(1) (wget would work too) :

[manual.md](https://github.com/fortran-lang/fpm/files/7532595/manual.md)

**Comment by urbanjost** [comment]
[manual.yml.txt](https://github.com/fortran-lang/fpm/files/7546566/manual.yml.txt)

made a github-actions file that does a wget of some scripts and runs them that successfully generates an HTML document.
Not a big user of these files (yet?).   How best to get the output file back to a web site,  and so on?

**Comment by awvwgk** [comment]
I started a repository for working on the user documentation at https://github.com/awvwgk/fpm-docs.

The documentation is mainly written in the MyST markdown dialect and rendered with sphinx, since I'm building via GitHub actions and deploy to GitHub pages we have the freedom to insert any additional generation steps in the workflow. John @urbanjost, we could try to incorporate the automatically generated markdown versions of fpm's help page in this documentation as well.

**Comment by urbanjost** [comment]
Not familiar with MyST markdown, but if it allows including HTML like github markdown that might give better results. Will take a look at MyST.

**Comment by urbanjost** [comment]
It says commonmark is a subset of MyST so I made a commonmark subdirectory in the fpm-tools/docs directory but I do not have an easy way to test it that I know of.  Do those look good?

**Comment by awvwgk** [comment]
New docs are up, lets move all further discussion about the documentation to https://github.com/fortran-lang/fpm-docs
