### ISSUE TITLE
Automatic finalization of objects in main program scope

### ISSUE THREAD

**Issue by ivan-pi** [fortran-lang/fpm#625]
After learning about the rules on automatic finalization and deallocation in the Discourse thread (https://fortran-lang.discourse.group/t/automatic-finalization-of-derived-types/2295/15), I was wondering if refactoring the [main](https://github.com/fortran-lang/fpm/blob/main/app/main.f90) program to use a block or subroutine would be a good idea?

This is not a bug report, but closer to an enhancement I suppose.

**Comment by awvwgk** [comment]
Seems like something easy to amend, if this is a problem. Feel free to open a pull request for proposing a patch.

**Comment by rouson** [comment]
I think this is unnecessary and not necessarily advisable unless required to address a specific problem.   See [my comments] in the cited Discourse thread.

[my comments]: https://fortran-lang.discourse.group/t/automatic-finalization-of-derived-types/2295/16?u=rouson

**Comment by ivan-pi** [comment]
Given that no specific problem has been encountered yet, I will close this for the time-being.
