### ISSUE TITLE
Don't require compiler field in fpm.toml

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#63]
Following up on the discussion in #60, let's remove the requirement for the `compiler` setting in the package-specific `fpm.toml`. 

For now, FPM should default to gfortran, and we can put a note in the README or the packaging guide that gfortran is currently the only compiler supported. We can relax this at a later time. The `compiler` setting can still remain in the toml parser as optional--perhaps we will want to allow package-specific choice of compiler.

**Comment by everythingfunctional** [comment]
That's reasonable for now. I'll make that change on my PR
