### ISSUE TITLE
fpm run and fpm test should emit a message if no action is taken

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#64]
Currently, if you issue `fpm run` in a library project without executable program, it does nothing.

It'd be more user friendly if we emitted a message to stderr, something like:

```
fpm: This package has no executable programs.
```

or similar.

Likewise for `fpm test`. If there are no test, we should say something like:

```
fpm: This package has no tests.
```

What do you think?

**Comment by everythingfunctional** [comment]
Not a bad idea. Shouldn't be too difficult to implement.
