### ISSUE TITLE
Cannot link C main

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#643]
I'm currently trying to (ab)use fpm to compile a C project. It is not a C package manager, but it certainly could become one.

Using a project with the following layout:

```
fpm.toml
app/main.c
```

`fpm.toml`:
```toml
name = "test"
[[executable]]
name = "test"
main = "main.c"
```

`app/main.c`:
```c
int
main (void) {
  return 0;
}
```

Will fail to link the C executable with

```
❯ fpm build
 + mkdir -p build/gfortran_2A42023B310FA28D/test
 + gcc -c app/main.c  -I./include -o build/gfortran_2A42023B310FA28D/test/app_main.c.o
❯ fpm run
<INFO> No executables to run
STOP 0
```

I think the source scanning must find a `program` statement in the source-file declared as `main` in the manifest. Instead, it would be preferable if fpm just trust the user input and assumes that the provided `main` is providing the necessary entry point.

---

Tested with fpm 0.5.0

**Comment by arjenmarkus** [comment]
How about faking that with:

/*
program my_c_program
*/
in the main.c source file?

Horrible hack, but it might work for now :).

Op ma 3 jan. 2022 om 16:03 schreef Sebastian Ehlert <
***@***.***>:

**Comment by awvwgk** [comment]
Fpm won't scan C source code for Fortran keywords, therefore it is not able to detect the program statement in the block comment.

**Comment by arjenmarkus** [comment]
It is being too smart ;). Or I am too wrapped up in today's debugging
session to think of such an obvious obstacle.

Op ma 3 jan. 2022 om 16:29 schreef Sebastian Ehlert <
***@***.***>:

**Comment by awvwgk** [comment]
The issue originates in `fpm_sources.f90` the branch for Fortran source code

https://github.com/fortran-lang/fpm/blob/d99ad594f731511413f5bad96f0c0dfe0c2c08aa/src/fpm_sources.f90#L30

can add an executable by setting the `exe_name` if a program unit was found

https://github.com/fortran-lang/fpm/blob/d99ad594f731511413f5bad96f0c0dfe0c2c08aa/src/fpm_sources.f90#L34-L36

the `else` branch for C source and headers is missing this capability.
