### ISSUE TITLE
osx/macos hidden files

### ISSUE THREAD

**Issue by lauvergn** [fortran-lang/fpm#649]
### Description

Recently, I've sent a fpm project as a tar file to students. One of them open it with a mac and some hidden files, ._xxx.f90, were created.
Then, "fpm build" fails because fpm try to compile the ._xxx.f90 files.
Of course removing the hidden files solves the problem.

### Expected Behaviour

Build the executable without removing the hidden files.

### Version of fpm

0.40 (osx) and 0.5.0 (linux)

### Platform and Architecture

MacOS, linux

**Comment by awvwgk** [comment]
Interesting behaviour, I wasn't aware this could happen.

One option for fpm would be to generally ignore all hidden files, the recursive listing of files currently discovers all files ending in `f90`. I think we can safely assume that projects hiding their source files don't want to compile those, right?

**Comment by lauvergn** [comment]
"I think we can safely assume that projects hiding their source files don't want to compile those, right?", indeed, I was expected that.

**Comment by awvwgk** [comment]
The source part of a project are collected with

https://github.com/fortran-lang/fpm/blob/2ae0581eb2a8f79d0cd0ff9d528de6e2fe827362/src/fpm_filesystem.F90#L379

which currently picks up all files. Having it skip hidden files and directories would solve this issue.

Alternatively, we can adapt the filter step here.

https://github.com/fortran-lang/fpm/blob/2ae0581eb2a8f79d0cd0ff9d528de6e2fe827362/src/fpm_sources.f90#L84-L87

We should transform the list of source files to their basename and than exclude all hidden files with leading zeros. However, this might be insufficient and still include a hidden directory, i.e. we have to check the canonical path for a pathseparator followed by a dot.

**Comment by noisegul** [comment]
I'd like to give this issue a try, if it is still free to be assigned.

**Comment by awvwgk** [comment]
Sure, feel free to send a patch for this issue. Let us know if you are stuck or need help at any point.

**Comment by noisegul** [comment]
Will do, thanks.

**Comment by noisegul** [comment]
@awvwgk Opened a PR.

**Comment by awvwgk** [comment]
Fixed by #654. Thanks, @noisegul.
