### ISSUE TITLE
How to build multiple programs?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#65]
Currently, FPM can build only one executable program, namely `main.f90`. 

Here's how [Cargo](https://doc.rust-lang.org/cargo/guide/project-layout.html) does it:

```
.
├── Cargo.lock
├── Cargo.toml
├── src/
│   ├── lib.rs
│   ├── main.rs
│   └── bin/
│       ├── named-executable.rs
│       ├── another-executable.rs
│       └── multi-file-executable/
│           ├── main.rs
│           └── some_module.rs
├── benches/
│   ├── large-input.rs
│   └── multi-file-bench/
│       ├── main.rs
│       └── bench_module.rs
├── examples/
│   ├── simple.rs
│   └── multi-file-example/
│       ├── main.rs
│       └── ex_module.rs
└── tests/
    ├── some-integration-tests.rs
    └── multi-file-test/
        ├── main.rs
        └── test_module.rs
```

So, for Fortran, the main executable could be `src/main.f90`, and other executables could go in `src/bin`. 

I like this approach, and I am not married to this particular directory structure. I also like the structure that we have now, namely `app/`, `src/`, `tests/`.

**Comment by everythingfunctional** [comment]
Right now, if you want multiple executables you have to specify them manually. I'm open to enabling some auto-detection of multiple executables. I'll put together an outline of what that would look like.

**Comment by certik** [comment]
I like the Cargo layout a lot. Brad, is there a reason to use app? I would switch to src/bin to be consistent with Cargo.

**Comment by LKedward** [comment]
I actually much prefer `app` to `src/bin`. In my mind a `bin` directory is for binary files only, not source code.

**Comment by certik** [comment]
Ok. Well, let's at least evaluate the options how to structure the layout with pros / cons. Because once we pick one, it will be hard to change.

**Comment by everythingfunctional** [comment]
The `app`, `src` separation makes it much easier to determine what should be packaged up into the library, and what is just for use in executable(s). I also makes finding the executable(s) a *bit* simpler for the automatically detected case. If we switch to the `src/bin` approach I'll need to special case out of searching that directory when building the library.

**Comment by certik** [comment]
I see, good point. Are we still doing `src/main.f90` to mean an executable? If so, then you have to special case this anyway.

**Comment by milancurcic** [comment]
I think we should aim to minimize special cases in the UI, and implement accordingly. A good test for this is asking what design leads to the simplest user guide.

For example, if everything in `src` is considered a library component except `src/main.f90` and `src/bin/*.f90`, then these are special cases that require additional clauses in the documentation.

On the other hand, `app` for programs and `src` for library is simplest to explain to a user, and is currently my favorite solution.

An even simpler UI than this (to explain to a user) is to have program files be programs, and module files be modules, regardless of where they are in the tree. However this complicates implementation because now fpm needs to parse the sources. A downside is that now there may not be clear separation between programs and module files if the user is just looking at the source tree. However if you have `app` and `src`, it's clear.

We should study Rust+Cargo model in detail, but we shouldn't assume that it's the optimal solution for us. This could be because of Rust's own history of the project, or because Rust and Fortran are different languages and have different cultures.

I agree with @LKedward about `app` vs `bin`.

**Comment by certik** [comment]
Good points. Note that `fpm` has to parse the sources anyway to determine module dependencies and to enforce that each module name is named appropriately.

So looks like the most natural solution so far is:

* `src` contains module files (or loose procedures / function --- we should not encourage it, but some existing projects do that and I think we can incorporate this without harm). Everything in `src` gets built into a library.
* `app`, contains programs. Perhaps `app/main.f90` could be the main program (by default executed by `fpm run`). 
* `tests` contains tests
* `bench` contains benchmarks (we can do this one later perhaps --- although most of my projects contain some kind of benchmarks which are distinct from apps and distinct from tests)

**Comment by everythingfunctional** [comment]
> I see, good point. Are we still doing `src/main.f90` to mean an executable? If so, then you have to special case this anyway.

No, I didn't implement `src/main.f90` to be an executable. If it sees that it will expect it to be a module named `main`.

**Comment by LKedward** [comment]
Closing as this is now implemented.
