### ISSUE TITLE
Provide debugging support for gdb

### ISSUE THREAD

**Issue by freevryheid** [fortran-lang/fpm#651]
### Description

It's not clear how to debug an fpm built app or library or how to map this against source code using gdb.

**Comment by awvwgk** [comment]
Adding `--runner gdb` to the fpm run or fpm test command will enable to run a target in the debugger.

**Comment by freevryheid** [comment]
That works, thanks. Needed to add the debug flag: fpm --profile=debug run solver --runner gdb
