### ISSUE TITLE
Support multiple compilers side-by-side in build

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fpm#66]
Currently compiled binaries are placed in `build/debug/` and `build/release`.
Would it be possible to make this build path dependent on compiler (and maybe architecture)?

_e.g._ `build/gfortran-9.2.0-x86_64_debug/`

This reason for this being that I like to build and test my projects on multiple compilers during development; separating the binary output paths allows incremental builds using multiple compilers and allows tests on each compiler to run simultaneously and without clean and rebuild.
This may be considered an _'ugly'_ directory structure, however since fpm handles all compiler/linker paths and offers the `fpm run` command, this has no effect on end-user experience.

The workflow for using a non-default compiler could then be along the lines of:

```
$> export FC=ifort
$> fpm run
```
or
```
$> FC=ifort fpm run
```
or
```
$> fpm run --compiler=ifort
```

**Comment by everythingfunctional** [comment]
Yeah, this shouldn't be too difficult. Good idea.

**Comment by awvwgk** [comment]
This has been resolved with https://github.com/fortran-lang/fpm/pull/255 in Fortran *fpm* and https://github.com/fortran-lang/fpm/pull/220 in the Haskell version.
