### ISSUE TITLE
fpm clean

### ISSUE THREAD

**Issue by freevryheid** [fortran-lang/fpm#664]
### Description

Proposing adding a new fpm command to delete the build folder. Sometimes, for whatever reason, programs fail to compile and the quick solution is to delete the build folder and recompile.  This happens when files are moved or new dependencies added/removed or changing the project name midway through development. 

### Possible Solution

Not sure we have a cross platform solution handy, but thinking along the lines of a system call: rm -rf build

### Additional Information

Can users have/use a custom folder other than 'build'? 
Dependency .git folders within build have write-protected files - force the delete.

**Comment by freevryheid** [comment]
PR https://github.com/fortran-lang/fpm/pull/665

**Comment by urbanjost** [comment]
I think this would also close #454

**Comment by freevryheid** [comment]
I've added the calling directory to settings if needed in the future. Also fixed the tests failing on added help clean text.

**Comment by vmagnin** [comment]
Yes, that feature is needed in every build system.
A few days ago, I renamed a dependency in the fpm.toml file of a project, but it did not provoke a rebuild.

I also think that fpm should detect when the fpm.toml of the project is modified, and provoke a rebuild.
