### ISSUE TITLE
New output for fpm test and/or fpm run breaks my CI

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#666]
### Description

`fpm run` or `fpm test` now includes `Project up to date` as part of the output produced if the project has already been built as part of PR #622. The test suite for my [iso_varying_string] library is now failing because one of the tests is for a procedure that does output, and this extra output is unexpected.

This is probably something I need to devise a better solution for in my test suite, but was an unexpected change. I think it deserves a bit of discussion whether we want this behavior though.

[iso_varying_string]: https://gitlab.com/everythingfunctional/iso_varying_string

### Expected Behaviour

`fpm test` or `fpm run` shouldn't output anything extra if the project is already up to date.

### Version of fpm

current

### Platform and Architecture

Linux

**Comment by milancurcic** [comment]
Good question and I agree. I think it's also idiomatic for a UNIX-style CLI application to emit no output if there is no error and there's "nothing" to report.

But I think this issue question can be clarified as "should `fpm build` emit output if the project is up-to-date", as `fpm test` and `fpm run` both implicitly invoke `fpm_build`, if I understand it correctly. I think the answer is no, it should not.

**Comment by everythingfunctional** [comment]
I'm not opposed to `fpm build` reporting up-to-date, as make would do, but it probably shouldn't be said for `fpm run` or `fpm test`. That complicates things a bit, but maybe not too much.

**Comment by urbanjost** [comment]
All messages that are informative should not appear unless the --verbose|-V switch is present; other possibilities are all messages go to stderr instead of stdout; and/or the user can set a verbosity level including no messages.  Having messages like that appear when using --list and --runner broke a lot of my scripts where I just wanted a pathname. Somewhat ironic it appears to have showed up along with the quiet mode for  building :>

**Comment by awvwgk** [comment]
It is not uncommon for build systems to report that there is no work to be done

```
❯ make
make: Nothing to be done for 'all'.
❯ ninja -C _build_gcc11/
ninja: Entering directory `_build_gcc11/'
ninja: no work to do.
```

**Comment by urbanjost** [comment]
And all that I know of write to stderr and/or have a quiet mode; as it the convention on GNU/Linux and Unix.  Even grep(1) has a quiet mode!

**Comment by Carltoffel** [comment]
I ran into this problem while following Milan's 'Modern Fortran' Book and doing it with `fpm`:
`fpm run > tsunami_output.txt` leads to `fpm`'s (re-)building output to appear in the output file, which then isn't parsable by the plotting routine.
IMHO all of `fpm`'s output should go to `stderr`.
Do you think an `toml` option for program output redirection could be useful?
