### ISSUE TITLE
Rationale for using Fortran Package Manager in 257 characters.

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/fpm#691]
I will [tweet](https://twitter.com/fortrantip) about fpm. I get 257 characters, since the link to https://fpm.fortran-lang.org/en/index.html will take 23 characters. What should I write to encourage people to try it? So far I have 251 characters:

```
Fortran Package Manager (fpm) lets you build a program or library, run
the executables, tests, and examples, and distribute it as a
dependency to other projects. It detects module dependencies, compiles
files in the proper order, and is more Fortran-aware than make.
```

Improvements are welcome. If it's fine as is please upvote.

**Comment by awvwgk** [comment]
Just link to https://fpm.fortran-lang.org this one automatically redirects and saves you 14 characters :upside_down_face:

**Comment by p-costa** [comment]
This + a link should fit a tweet:
```
Fortran Package Manager (fpm) lets you build a program/library, run
the executables/tests/examples, and distribute it as a
dependency to other projects. It detects module dependencies, compiles
files in the proper order, being more Fortran-aware than make
```

**Comment by Beliavsky** [comment]
> Just link to https://fpm.fortran-lang.org this one automatically redirects and saves you 14 characters 🙃

[All Twitter links take 23 characters](https://help.twitter.com/en/using-twitter/how-to-tweet-a-link).

**Comment by Beliavsky** [comment]
[Tweeted](https://twitter.com/fortrantip/status/1517462836062081024).

**Comment by awvwgk** [comment]
Thanks, closing this as resolved than.
