### ISSUE TITLE
FPM pip installation

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/fpm#705]
## Description

This is a follow up from this discussion: https://github.com/fortran-lang/fpm/discussions/696
The short summary is that if we wish to deploy `fpm` through VS Code it would be easier to do so through `pip` rather than `conda`.

## Solution

We would have to build the binary for multiple distributions and package them in a bdist python wheel.

### TODO:

- [x] Claim via [PEP 541 request](https://github.com/pypa/pypi-support/issues/new?assignees=&labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME) the `fpm` from the name squatter.

### Building Python wheels cross-platform

1. ``cibuildwheel` and use an GitHub Actions CI to build the multiple wheels: [CMake build](https://github.com/scikit-build/cmake-python-distributions/blob/master/.github/workflows/build.yml) can server as a good example and [cibuildwheel](https://github.com/pypa/cibuildwheel)
2. Use `scikit-build` and `CMake` to build fpm (uses `cibuildwheel` in the background). That seems to be the easiest way although it will be slightly ironic.
3. Use [`conda-smithy`](https://conda-forge.org/docs/user/ci-skeleton.html). I think we will have to set up the Azure pipelines ourselves. I don't have any experience with that. @awvwgk I don't know if you have any advice on how to get started.

### Additional Information

1. I am still uncertain as to how to build wheels for M1/M2 computers.
4. CMake uses `qemu` which AFAIK is not offered directly from a GitHub Action, so we would have to figure out how to set up a workflow.

**Comment by kjelljorner** [comment]
A comment on building wheels for Apple Silicon - I've thought a lot about this and I think you have three options at the moment:

1. Self-hosted CI runner
2. Cross-compiling - this is what they do on [conda-forge](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/)
3. Manually building on your own machine

I had some [success](https://github.com/kjelljorner/libconeangle) with using [scikit-build](https://scikit-build.readthedocs.io/en/latest/) which takes care of thinking about `setup.py`. You can check out my setup for building wheels on GitHub Actions [here](https://github.com/kjelljorner/libconeangle/blob/main/.github/workflows/build_wheels.yml) (not for M1 as they don't have runners). I think I have read somewhere that you could in principle hi-jack the conda-forge CI to build wheels at the same time as you [build](https://github.com/conda-forge/fpm-feedstock/tree/main/recipe) fpm for Apple Silicon, but I'm not sure that they would look kindly on that 😄

**Comment by awvwgk** [comment]
> I think I have read somewhere that you could in principle hi-jack the conda-forge CI to build wheels at the same time as you [build](https://github.com/conda-forge/fpm-feedstock/tree/main/recipe) fpm for Apple Silicon, but I'm not sure that they would look kindly on that smile

I have been using the conda-forge setup (the docker images and the (cross-)compiler toolchains) for building wheels. For Linux this works fine, but you have to be careful, since the GLIBC version in the comp7 image is too old to run GH actions, the cos7 image is fine.

For MacOS however there is a problem with delocate, which cannot pickup the libraries from the conda environment due to rpath linking correctly, the (cross-)compilation itself works fine. Not sure how easy this can be fixed.

We could also use the conda-forge CI setup, since the tooling is all available and open for exactly this reason.

**Comment by kjelljorner** [comment]
Is this a problem with the rpaths of the conda libs being wrong, or that delocate will not pick them up? In principle we could copy the libs to a custom directory and modify the runpaths.

**Comment by MuellerSeb** [comment]
For a nice working example, you could have a look here (skbuild based):
https://github.com/ssciwr/clang-format-wheel

**Comment by gnikit** [comment]
They use scikitbuild which we can't because we don't make use of cmake. We would have to keep a cmake installation alongside the fpm one or have a dummy cmake installation that calls fpm build and fpm install. Then we have to repair the wheels because we use libc, which is not necessarily easy.
