### ISSUE TITLE
gitignore file should ignore mod files

### ISSUE THREAD

**Issue by radekg** [fortran-lang/fpm#732]
### Description

I have noticed that the fpm produces a single `build/.gitignore` file with the content of `*`. My understanding is that `mod` files aren't portable and so they should not end up in git. Thus they should be in `.gitignore`.

### Possible Solution

The place where this file is generated is here: https://github.com/fortran-lang/fpm/blob/main/src/fpm.f90#L62-L65.

IMHO, it would be better to have a top-level `.gitignore` file with the following lines:

```
build/**
*.mod
```

Sounds like a very simple change and I could prepare a PR.

**Comment by awvwgk** [comment]
Modulefiles should be produced inside the build directory, by ignoring all of its content the mod files are already excluded as well.

**Comment by radekg** [comment]
Ah, I see. So I need to figure out how to make my Modern Fortran vsc extension always store and pick up mod files from the build directory.  
What confused me was that when adding new module in vsc, the extension automatically places the mod file next to the source, in `src/`. I guess I need to raise that with the vsc extension manintainer.
