### ISSUE TITLE
Unable to find dependency from parent directory when building exe 

### ISSUE THREAD

**Issue by samharrison7** [fortran-lang/fpm#734]
### Description

I am trying to build an executable from a project with the following structure:

```
src/
  a/
    a_mod.f90
  b_mod.f90
  main.f90
```

In the code, `a_mod` uses `b_mod`, and `main` uses `a_mod`. When I build just as a library, it works as expected. However, when I specify to build an executable from `main.f90`, the build fails with the error `<ERROR>*cmd_build*:target error:Unable to find source for module dependency: "b_mod" used by "./src/a/a_mod.f90"`.

The issue seems to occur when a module depends on a module that is in a parent directory (i.e. `a_mod` depending on `b_mod` from its parent directory) and only when build an executable.

I have placed a minimum viable example of the project structure that causes this issue in this repo: https://github.com/samharrison7/fpm-test-exe-issues

### Expected Behaviour

I expected `fpm` to build the executable from this project structure.

### Version of fpm

0.6.0, alpha

### Platform and Architecture

Ubuntu 20.04

**Comment by zoziha** [comment]
Thanks for your feedback @samharrison7 , it seems that this problem does exist.

In `fpm.f90`, `fpm` first parses the main program source files, and labels these source files with `FPM_SCOPE_APP, FPM_SCOPE_EXAMPLE, FPM_SCOPE_TEST`, then parses the module source files, and labels `FPM_SCOPE_LIB, FPM_SCOPE_DEP`, and only `FPM_SCOPE_LIB, FPM_SCOPE_DEP` labelled source files are Will be queried if provide the module names (see [find_module_dependency](https://github.com/fortran-lang/fpm/blob/1f2831f5a37fe49bd549d6eeafcb091ef9ce6bdb/src/fpm_targets.f90#L462)).

A feasible solution is to parse the dependency source files first, and then parse those main programs.

**Comment by samharrison7** [comment]
Thanks for the quick response and fix @zoziha! I've just tested your patch on my code (including a much more complicated version of the minimum example I posted) and it compiles the exe without problems now.

**Comment by LKedward** [comment]
Hi @samharrison7 - this behaviour is currently part of the [intended design](https://github.com/fortran-lang/fpm/issues/408#issuecomment-805151909) of fpm. Modules that are not in the main `src` directory are not part of the library and have a use scope limited to the folder they are in and subfolders. Apologies that this is not documented anywhere for users. It is documented for developers [here](https://fortran-lang.github.io/fpm/proc/resolve_module_dependencies.html).

**Comment by samharrison7** [comment]
Ah I did wonder whether it was a design thing. That seems a logical restriction and is probably a good motivation for me to do some src directory restructuring of my projects!

**Comment by samharrison7** [comment]
Though I do wonder whether having a flag to override this restriction would be a useful addition for legacy projects where directory restructuring isn't possible/desirable?

**Comment by LKedward** [comment]
> Though I do wonder whether having a flag to override this restriction would be a useful addition for legacy projects where directory restructuring isn't possible/desirable?

Yes, this is a good point, though it'll have to be an option in the manifest file instead of a flag.

**Comment by zoziha** [comment]
@LKedward ，if I'm not mistaken, #734 doesn't seem to change the original intention of the design you mentioned.
> 1. Library sources (FPM_SCOPE_LIB) may only use modules also with library scope. This includes library modules from dependencies.
> 2. Executable sources (FPM_SCOPE_APP,FPM_SCOPE_TEST) may use library modules (including dependencies) as well as any modules corresponding to source files in the same directory or a subdirectory of the executable source file.

```sh
src
    a/
        a_mod.f90
    b_mod.f90
    main.f90
---
# fpm.toml
[[executable]]
name = "main"
source-dir = "src"
main = "main.f90"
```
The above demo **can** be compiled normally in the #734 patch because `src` defaults to the library file path and `a_mod.f90` obeys the rule 1 and can access the parent folder (`src`), both `a_mod.f90` and `b_mod.f90` belong to the same `FPM_SCOPE_LIB`.

```sh
app
    a/
        a_mod.f90
    b_mod.f90
    main.f90
---
# fpm.toml
[[executable]]
name = "main"
source-dir = "app"
main = "main.f90"
```
The above demo **cannot** be compiled normally in the #734 patch because the `app` defaults to the executable program file path. Both `a_mod.f90` and `b_mod.f90` belong to `FPM_SCOPE_APP`, and an error will appear:
```sh
<ERROR>*cmd_build*:target error:Unable to find source for module dependency: "b_mod" used by "./src/a/a_mod.f90"
```
The reason is that `a_mod.f90` obeys the rule 2 and cannot access the parent folder.

**Comment by LKedward** [comment]
Thanks for explaining @zoziha, that makes sense to me now.
