### ISSUE TITLE
Undefined reference to function while compiling .c and .cpp files.

### ISSUE THREAD

**Issue by arteevraina** [fortran-lang/fpm#741]
After this [PR](https://github.com/fortran-lang/fpm/pull/733) got merged in the main branch.  I tried to compile `stdlib` using new build of fpm. I was still getting the same error 

```
test/hash_functions/test_hash_functions.f90 which is giving me this error :
undefined reference to generate_all_c_hash

```

This issue is not just limited to .cpp files, but .c files also show the same error while compiling. To test that out, I have created a modified version of `with_c` example for testing. You can check this out [here](https://github.com/arteevraina/reproducible-example-with-c).

**FPM VERSION** : I am running the executable fpm version of the current `main` branch.

**Logs for Reproducible Example**
```

(env) arteev@pavilion:~/reproducible-example$ fpm build
c_code.c                               done.
with_c.f90                             done.
libwith_c.a                            done.
main.f90                               done.
with_c                                 failed.
[100%] Compiling...
/usr/bin/ld: build/gfortran_2A42023B310FA28D/with_c/libwith_c.a(src_with_c.f90.o): in function `__with_c_MOD_system_isdir':
/home/arteev/reproducible-example/./src/with_c.f90:22: undefined reference to `my_isdir'
collect2: error: ld returned 1 exit status
<ERROR> Compilation failed for object " with_c "
<ERROR>stopping due to failed compilation
STOP 1



```

**Show Model for Reproducible Example**

```
(env) arteev@pavilion:~/reproducible-example$ fpm build --show-model|sed "s/,/,\n/g" -
 fpm_model_t(package_name="with_c",
 packages=[package_t(name="with_c",
 sources=[srcfile_t(file_name="app/c_code.c",
 exe_name="",
 unit_scope=FPM_SCOPE_APP,
 modules_provided=[],
 parent_modules=[],
 unit_type=FPM_UNIT_CSOURCE,
 modules_used=[],
 include_dependencies=[],
 link_libraries=[],
 digest=-4855192256658658792),
 srcfile_t(file_name="app/main.f90",
 exe_name="with_c",
 unit_scope=FPM_SCOPE_APP,
 modules_provided=[],
 parent_modules=[],
 unit_type=FPM_UNIT_PROGRAM,
 modules_used=["with_c"],
 include_dependencies=[],
 link_libraries=[],
 digest=9186979595472880402),
 srcfile_t(file_name="./src/with_c.f90",
 exe_name="",
 unit_scope=FPM_SCOPE_LIB,
 modules_provided=["with_c"],
 parent_modules=[],
 unit_type=FPM_UNIT_MODULE,
 modules_used=[],
 include_dependencies=[],
 link_libraries=[],
 digest=6240126590444891773)])],
 compiler=(fc="gfortran",
 cc="gcc"),
 archiver=(ar="ar -rs "),
 fortran_compile_flags=" -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single",
 c_compile_flags="",
 cxx_compile_flags="",
 link_flags="",
 build_prefix="build/gfortran",
 link_libraries=[],
 external_modules=[],
 deps=dependency_tree_t(...))
```

cc: @awvwgk @LKedward @jvdp1 @zoziha

**Comment by arteevraina** [comment]
@awvwgk I remember in yesterday's meeting, we moved .c and .cpp files out of the `src` directory to either `app` directory or `test` directory (as we can see in r[eproducible example](https://github.com/arteevraina/reproducible-example-with-c)). Does that mean they are working fine in `src` directory and we have to fix it for `app` and `test` directory only ?

**Comment by jvdp1** [comment]
> Does that mean they are working fine in `src` directory and we have to fix it for `app` and `test` directory only ?

Yes, it works fine when the `.c` file is in the `src` directory.
Note that the same case with Fortran files only works fine.

**Comment by arteevraina** [comment]
When I try to compile the [reproducible project](https://github.com/arteevraina/reproducible-example-with-c) with `with_c.f90` & `c_code.c` file in src directory and run `fpm build --verbose`, the log which shows archive being generated has two object files in command `src_c_code.c.o`  & `src_with_c.f90.o`, but on the other hand if I try to compile reproducible example as it is. I can only see only one object file `src_with_c.f90.o` in command line. I think this might also be one of the reasons for linker issue ?

### Logs when `with_c.f90` && `c_code.c` are in `src` directory
```
 <INFO> BUILD_NAME: build/gfortran
 <INFO> COMPILER:  gfortran
 <INFO> C COMPILER:  gcc
 <INFO> CXX COMPILER: g++
 <INFO> COMPILER OPTIONS:   -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single
 <INFO> C COMPILER OPTIONS:  
 <INFO> CXX COMPILER OPTIONS: 
 <INFO> LINKER OPTIONS:  
 <INFO> INCLUDE DIRECTORIES:  []
 + mkdir -p build/gfortran_2A42023B310FA28D
 + mkdir -p build/gfortran_00000000811C9DC5
[  0%]                       c_code.c
 + mkdir -p build/gfortran_00000000811C9DC5/with_c/
 + gcc -c ./src/c_code.c  -o build/gfortran_00000000811C9DC5/with_c/src_c_code.c.o
[ 20%]                       c_code.c  done.
[ 20%]                     with_c.f90
 + mkdir -p build/gfortran_2A42023B310FA28D/with_c/
 + gfortran -c ./src/with_c.f90  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o build/gfortran_2A42023B310FA28D/with_c/src_with_c.f90.o
[ 40%]                     with_c.f90  done.
[ 40%]                    libwith_c.a
 + ar -rs build/gfortran_2A42023B310FA28D/with_c/libwith_c.a build/gfortran_00000000811C9DC5/with_c/src_c_code.c.o build/gfortran_2A42023B310FA28D/with_c/src_with_c.f90.o
ar: creating build/gfortran_2A42023B310FA28D/with_c/libwith_c.a
[ 60%]                    libwith_c.a  done.
[ 60%]                       main.f90
 + gfortran -c app/main.f90  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o build/gfortran_2A42023B310FA28D/with_c/app_main.f90.o
[ 80%]                       main.f90  done.
[ 80%]                         with_c
 + mkdir -p build/gfortran_2A42023B310FA28D/app/
 + gfortran  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single  build/gfortran_2A42023B310FA28D/with_c/app_main.f90.o build/gfortran_2A42023B310FA28D/with_c/libwith_c.a -o build/gfortran_2A42023B310FA28D/app/with_c
[100%]                         with_c  don
```

### Logs when we run reproducible example as it is.

```
 <INFO> BUILD_NAME: build/gfortran
 <INFO> COMPILER:  gfortran
 <INFO> C COMPILER:  gcc
 <INFO> CXX COMPILER: g++
 <INFO> COMPILER OPTIONS:   -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single
 <INFO> C COMPILER OPTIONS:  
 <INFO> CXX COMPILER OPTIONS: 
 <INFO> LINKER OPTIONS:  
 <INFO> INCLUDE DIRECTORIES:  []
 + mkdir -p build/gfortran_2A42023B310FA28D
 + mkdir -p build/gfortran_00000000811C9DC5
[  0%]                       c_code.c
 + mkdir -p build/gfortran_00000000811C9DC5/with_c/
 + gcc -c app/c_code.c  -o build/gfortran_00000000811C9DC5/with_c/app_c_code.c.o
[ 20%]                       c_code.c  done.
[ 20%]                     with_c.f90
 + mkdir -p build/gfortran_2A42023B310FA28D/with_c/
 + gfortran -c ./src/with_c.f90  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o build/gfortran_2A42023B310FA28D/with_c/src_with_c.f90.o
[ 40%]                     with_c.f90  done.
[ 40%]                    libwith_c.a
 + ar -rs build/gfortran_2A42023B310FA28D/with_c/libwith_c.a build/gfortran_2A42023B310FA28D/with_c/src_with_c.f90.o
ar: creating build/gfortran_2A42023B310FA28D/with_c/libwith_c.a
[ 60%]                    libwith_c.a  done.
[ 60%]                       main.f90
 + gfortran -c app/main.f90  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -J build/gfortran_2A42023B310FA28D -Ibuild/gfortran_2A42023B310FA28D -o build/gfortran_2A42023B310FA28D/with_c/app_main.f90.o
[ 80%]                       main.f90  done.
[ 80%]                         with_c
 + mkdir -p build/gfortran_2A42023B310FA28D/app/
 + gfortran  -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single  build/gfortran_2A42023B310FA28D/with_c/app_main.f90.o build/gfortran_2A42023B310FA28D/with_c/libwith_c.a -o build/gfortran_2A42023B310FA28D/app/with_c
/usr/bin/ld: build/gfortran_2A42023B310FA28D/with_c/libwith_c.a(src_with_c.f90.o): in function `__with_c_MOD_system_isdir':
/home/arteev/reproducible-example/./src/with_c.f90:22: undefined reference to `my_isdir'
collect2: error: ld returned 1 exit status
[100%]                         with_c  done.

/usr/bin/ld: build/gfortran_2A42023B310FA28D/with_c/libwith_c.a(src_with_c.f90.o): in function `__with_c_MOD_system_isdir':
/home/arteev/reproducible-example/./src/with_c.f90:22: undefined reference to `my_isdir'
collect2: error: ld returned 1 exit status
<ERROR> Compilation failed for object " with_c "
<ERROR>stopping due to failed compilation
STOP 1
```

cc: @awvwgk

**Comment by LKedward** [comment]
Thanks for looking into this @arteevraina and apologies for the late response from myself. I think this is actually the same problem as #556. fpm currently only links executables to the library and to any module sources in the same directory (or a subdirectory). We can probably now update this to simply link executables with __any targets with source files in the same directory__ (or a subdirectory). The relevant routine to look at is [`resolve_target_linking`](https://github.com/fortran-lang/fpm/blob/257097593bd98246f0cfc0015a4ae6ae4fe11f87/src/fpm_targets.f90#L713) and specifically `get_link_objects` which currently loops over module dependencies of executable targets. This can be changed to loop over all targets and link any non-library targets that have source files in the right location. Hope that makes sense, let me know if not!

**Comment by zoziha** [comment]
> We can probably now update this to simply link executables with **any targets with source files in the same directory** (or a subdirectory).

We can probably now update this to simply link executables with **any targets with _`C/C++`_ source files in the same directory** (or a subdirectory).

It seems that `fpm` cannot detect dependencies between `Fortran` sources and `C/C++` sources, and eventually, `C/C++` source files under the `app/` path are ignored at link time.

(Based on [reproducible project](https://github.com/arteevraina/reproducible-example-with-c), I got a more simplified version repository branch [reproducible project](https://github.com/zoziha/reproducible-example-with-c/tree/patch-1).)

**Comment by LKedward** [comment]
> We can probably now update this to simply link executables with **any targets with _`C/C++`_ source files in the same directory** (or a subdirectory).

No, I believe my original statement stands correct because we also need to link to non-module Fortran sources which are also not currently linked with executables (hence #556).

> It seems that `fpm` cannot detect dependencies between `Fortran` sources and `C/C++` sources, and eventually, `C/C++` source files under the `app/` path are ignored at link time.

There's no hard necessity for fpm to detect this from the source file content - fpm only needs to know about Fortran *module dependencies* to get the compilation order correct. We infer the link-time dependency based on the presence of the source file in the folder.

**Comment by LKedward** [comment]
fyi, I'm now working on a patch for this (and #556)
