### ISSUE TITLE
Add lib prefix to the static library file name

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#75]
Currently, FPM emits a static library file that has the same name as the project. For example, first line of `fpm.toml` could be:

```toml
name = "datetime"
```

Then, the static library created is `datetime.a`. However, the canonical way to name libraries (static and dynamic) is to use a `lib` prefix: `libdatetime.a`. Then one can link to this library with `-ldatetime`. 

Current workaround can be to add the `lib` prefix to the package name in `fpm.toml`:

```toml
name = "libdatetime"
```

However, this isn't pretty, and would down the road be more awkward once we're installing packages from remote URLs. 

Let's add the `lib` prefix to library files.

**Comment by certik** [comment]
I agree.

**Comment by everythingfunctional** [comment]
I see. This is a simple enough change to make. I will note however that FPM is just including the archive directly in the link command, rather specify both `-Ilib/folder` and `-lname` arguments. So this will only impact users doing things outside of FPM. Granted that many people *will* want to do things outside of FPM, I think it makes sense to go ahead and do it.
