### ISSUE TITLE
Should we refer to this software as FPM or fpm?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#77]
They mean the same, but they look and "feel" different. We should have a consistent way to refer to this so it's not confusing to the readers whether they're different things. Especially as we begin to write about these things more publicly?

I've been using both. I don't know which one I prefer. Perhaps 60/40 in favor of fpm. 

So, which one should it be?

**Comment by certik** [comment]
I've been using both also. Let's use lowercase.

I think fpm, with `fpm` in markdown. Just like git or markdown.

If it is at the beginning of a sentence, let's use Fpm.

**Comment by certik** [comment]
I guess git uses both Git and git: https://git-scm.com/

I think svn also uses both SVN and svn.

I am fine either way.

We can have a rule to use FPM when referencing the project, but fpm when the executable, and encourage to use fpm where it make sense. But should we write Fortran Package Manager (FPM) or Fortran Package Manager (fpm) at the top of the website?

Ondrej

**Comment by milancurcic** [comment]
[Node Package Manager](https://www.npmjs.com/) uses npm universally. Even the company is called "npm, Inc.".

I vote for fpm all the way, and `fpm` when referring specifically to the command line executable.

**Comment by certik** [comment]
I also vote fpm all the way.

**Comment by everythingfunctional** [comment]
I can come up with logical arguments for either.

On the one hand, it's a proper noun, Fortran is capitalized, and it's an acronym, so FPM would make sense.

On the other hand, Fortran is a case insensitive language, and our community style guide seems to be leaning towards all lowercase, so fpm would be consistent with that.

Given that this really is a purely aesthetic choice, and there seems to be a trend in other places towards all lowercase, I have nothing against using fpm everywhere. I'll start doing that.

**Comment by milancurcic** [comment]
The consensus so far is to use "fpm" everywhere. Closing.
