### ISSUE TITLE
Static link executables attached to release

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#780]
I just encountered a situation where fpm stopped working in the MacOS CI on one of my projects. Apparently GitHub recently changed the MacOS CI environment to no longer include one of the older gfortran run-time libraries that the fpm release is apparently dynamically linked against. We should probably make it standard practice that the fpm executable available from the release page is fully self-contained (e.g. fully static linked) to prevent things like this from breaking.

On a side note, it may also be desirable for the fpm action to test that fpm works correctly once installed. I'll open an issue on that repo to track it there.

FYI, the immediate workaround is to add `brew install gcc@9` to any MacOS CI scripts that need to execute fpm.

**Comment by LKedward** [comment]
Thanks for reporting. Sadly, I don't think there's much we can do about this.

> We should probably make it standard practice that the fpm executable available from the release page is fully self-contained (e.g. fully static linked) to prevent things like this from breaking.

Recall discussion in https://github.com/fortran-lang/fpm/issues/356#issuecomment-778310194 about the inability to statically link on MacOS. (The Windows and Linux release binaries are already statically linked.)

Do you get the same issue if you [install fpm with brew](https://fpm.fortran-lang.org/en/how-to/installation.html#homebrew-package-manager)?

**Comment by awvwgk** [comment]
There is nothing we can do with respect to static linking on MacOS as this is not supported by the platform itself. Since the Fortran runtime is foreign to the default system it requires the user to provide the correct runtime libraries to allow dynamic linking.
