### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#83]
Currently the new fpm does not seem to have any tests. We have to fix it, and start adding lots of tests.

In the old fpm, I had two initial tests:

https://github.com/fortran-lang/fpm/tree/master/archive/tests

And we need to add a lot more. The idea would be to test any configuration that is supported, and that way we can ensure that it works and things don't break when new functionality is implemented.

Furthermore, if we decide to use a different language for the production implementation, the tests will allow us to ensure that the new implementation works as expected.

**Comment by awvwgk** [comment]
This should be resolved with the current status of CI testing.
