### ISSUE TITLE
Install script broken?

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/fpm#836]
### Description

Did something recently change to break the install script? I just had a [build failure](https://gitlab.com/everythingfunctional/dockerfpm/-/jobs/3722858510) on my [dockerfpm](https://gitlab.com/everythingfunctional/dockerfpm) project that seems to indicate the install script couldn't find the latest release.

### Expected Behaviour

The install script should work within an Ubuntu based Docker image.

### Version of fpm

latest

### Platform and Architecture

Docker image based on ubuntu:rolling

### Additional Information

A `git blame` seems to indicate the change from #818 may be the culprit.

**Comment by perazz** [comment]
@everythingfunctional You're right, it seems like `curl` is not supplied by default on Ubuntu: 

```
#10 0.237 ./install.sh: 24: curl: not found
```

**Comment by everythingfunctional** [comment]
That's because the next lines are the important part:

```
#10 0.242 --2023-02-06 17:19:47--  https://github.com/fortran-lang/fpm/releases/download/v/fpm-.F90
#10 0.245 Resolving github.com (github.com)... 140.82.113.3
#10 0.249 Connecting to github.com (github.com)|140.82.113.3|:443... connected.
#10 0.280 HTTP request sent, awaiting response... 404 Not Found
#10 0.373 2023-02-06 17:19:47 ERROR 404: Not Found.
```

It's not that `curl` wasn't found, it's that `curl` didn't find anything at the provided url. Notice the missing version identifier in `https://github.com/fortran-lang/fpm/releases/download/v/fpm-.F90`

**Comment by perazz** [comment]
#839 should solve this issue, where to test the install script?

**Comment by everythingfunctional** [comment]
I've tried it out locally and it seems to work.

**Comment by vmagnin** [comment]
I have just tried installing fpm on a Debian Sid 32bits, after a `git clone`:
```bash
osboxes@osboxes:~/fpm$ ./install.sh
--2023-02-17 18:51:30--  https://api.github.com/repos/fortran-lang/fpm/releases/latest
Resolving api.github.com (api.github.com)... 140.82.121.6
Connecting to api.github.com (api.github.com)|140.82.121.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘latest’

latest                                    [ <=>                                                                      ]  27.15K  --.-KB/s    in 0.05s   

2023-02-17 18:51:31 (503 KB/s) - ‘latest’ saved [27806]

--2023-02-17 18:51:31--  https://github.com/fortran-lang/fpm/releases/download/v/fpm-.F90
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-02-17 18:51:31 ERROR 404: Not Found
```

After a `$ sudo apt install curl`, the install script worked fine.

**Comment by vmagnin** [comment]
I think, I have `git clone` just 20 minutes ago.

**Comment by perazz** [comment]
https://github.com/fortran-lang/fpm/blob/5efb9e062bd8341ea7309af6eeb7172627a594b9/install.sh#L74 

this line is to blame, it should be 
```
LATEST_RELEASE=$(get_latest_release "fortran-lang/fpm" "$FETCH")
```
