### ISSUE TITLE
fpm sometimes does not properly rebuild the project when module internals are changed

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#838]
I don't have a minimal reproducer yet, but a few times this fails:
```
fpm run
```
And this fixes it:
```
fpm clean
fpm run
```

I am opening up an issue for this, as there is almost for sure a bug in fpm, I just have to create a reproducer and then we can work on fixing it and adding a test for this.

**Comment by perazz** [comment]
I had found that `cache.toml` is almost never rebuilt (see https://github.com/fortran-lang/fpm/pull/800/commits/2b708142954437c04307c8baf520947d456feae9, then closed, it did not see a package changing name). Maybe fpm needs a mechanism that triggers a full re-build whenever _any_ changes are detected in the dependency tree?

**Comment by perazz** [comment]
I believe this should have been fixed by #843.

**Comment by perazz** [comment]
As released in 0.8.1 #874 .
