### ISSUE TITLE
make `fpm new` automatically add a line to fpm.toml to enforce prefixes for module names

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#854]
This should be added:
```
module-naming = true
```
together with the minimal required version (#855). The new package author can decide, what version should be required. If older version is required, then the author can remove the `module-naming` line.

There is an issue that if we do that, and build the project with an older fpm version, it will fail to build, see https://github.com/toml-f/toml-f/pull/121 for an example of that. The solution to this is described at https://github.com/fortran-lang/fpm/issues/855.

**Comment by perazz** [comment]
I will close this as completed, thank you @certik.
