### ISSUE TITLE
fpm doesn't recognize .f extension

### ISSUE THREAD

**Issue by rouson** [fortran-lang/fpm#863]
### Description

There seem to be at least 5 issues that have discussed fixed source form and/or the `.f` extension: #250, #359, #363, #366, #367.  I don't have a strong opinion about the best path forward, but I suspect that any of the previously suggested options would be preferable to the status quo.  From the test transcript below, I gather that `fpm` currently doesn't recognize files with the `.f` extension as Fortran source files.  However, if a file has the extension `.f90` and contains fixed-form source, then `fpm build --flag "-ffixed-form"` succeeds (with `gfortran`). This has the counter-intuitive effect that a file containing fixed-form source must have a name with an extension that is the _opposite_ of `gfortran`' s default convention in order for `fpm build` to work.  Is there a decision-making process that can be used to decide which of the many suggested paths forward to choose?  Even if the chosen solution doesn't get implemented right away, at least making a decision could facilitate closing some of the aforementioned issues so that people searching the open issues will find only the chosen path rather than all of the alternatives considered.

```
% tree .
.
├── app
│   └── main.f
└── fpm.toml

1 directory, 2 files

% cat fpm.toml 
name = "hello"
version = "0.1.0"
author = "Damian Rouson"
maintainer = "damian@archaeologic.codes"

% cat app/main.f 
      program main
        implicit none
        print *,"Hello, world!" 
      end program main

% fpm build --flag "-ffixed-form" 
<ERROR>*cmd_build*:package error:Neither library nor executable found, there is nothing to do
STOP 1

% mv app/main.f{,90}

% fpm build --flag "-ffixed-form"
 + mkdir -p build/dependencies
main.f90                               done.
hello                                  done.
[100%] Project compiled successfully.
```

### Expected Behaviour

I would expect files with the `.f` extension to at least be recognized as Fortran source files independent of whether the default is to treat them as fixed or free source form.

### Version of fpm

0.7.0

### Platform and Architecture

macOS/ARM

**Comment by certik** [comment]
CC @awvwgk, @milancurcic, @LKedward, @gnikit, @everythingfunctional, and others, it's time to make a decision on this. My preferred solution is https://github.com/fortran-lang/fpm/issues/363.

**Comment by milancurcic** [comment]
There's agreement in #363. Implementor is needed.

**Comment by rouson** [comment]
It seems that the problem reported in this issue only arises when the main program in `app/` doesn't `use` and modules from `src/`, which of course happens in the reported case because there is no `src/` subdirectory.  Adding a module in `src/` and a corresponding `use` statement in the main program in `app/` fixes the problem.  I now think this is was maybe too trivial issue to report.  Presumably there's a design assumption that if someone is using a build system, there must be some dependencies between files to sort out.  Otherwise, there's not a lot of motivation to use a build system.  I'm going to close this issue.  If anyone thinks it's important enough to reopen, feel free to do so.

**Comment by everythingfunctional** [comment]
@rouson , I'd have to investigate a bit to be sure, but I suspect it is that the expected default name of the main program in `app` is `main.f90`. It's not immediately clear to me how adding a use statement would work around that expectation, but I'm happy you were able to figure out a workaround.
