### ISSUE TITLE
Force user to specify single version of a dependency if it is requested by multiple packages

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/fpm#867]
### Description

If we have a dependency, let's say `toml-f`, and then we have another dependency, e.g. `jonquil`, that imports `toml-f`, we might have the case where two different versions of `toml-f` are requested within the same project. Since we currently haven't implemented version constraints, the default way is to specify a sha or tag. If two different versions of a dependency are requested within a project, I'd expect an error message, forcing the user to use the same version, but that is currently lacking in fpm.

To reproduce:

- Checkout `main`.
- Remove `build` folder to make sure.
- Add dependency:

```
jonquil.git = "https://github.com/toml-f/jonquil"
jonquil.rev = "05d30818bb12fb877226ce284b9a3a41b971a889"
```
- Run `fpm install`
- Run `~/.local/bin/fpm build`

You will get:

```bash
# Dependency change detected: toml-f
# Dependency change detected: toml-f
```

There are obviously conflicts, but these aren't resolved but more or less ignored.

It's also a follow-up to https://github.com/fortran-lang/fpm/pull/843. @perazz

### Expected Behaviour

Display error message and inform user which are the conflicting dependencies. The best case would be to also inform the user which versions (sha, tag) are currently requested for which dependency so the user can copy/paste to resolve the problem.

### Version of fpm

main, 55d94b0eb5685b2214ea7c2f2039ba7e9c7bf418

### Platform and Architecture

MacOS/ARM

**Comment by perazz** [comment]
Superseded by #870 and closed by #871, #873, #875.
