### ISSUE TITLE
Feature: Modify a profile for a specific dependency

### ISSUE THREAD

**Issue by rouson** [fortran-lang/fpm#899]
### Description

In attempting to build [netcdf-interfaces] as a dependency of [inference-engine], I find that `fpm` 0.8.1 breaks [netcdf-interfaces] because the following profiles pass `-Werror=implicit-interface` to `gfortran`, whereas `fpm` 0.7.0 passes `-Wimplicit-interface`:
* no `--profile`
* `--profile debug`
* `--profile release`

What's the best way to adjust for this change in `fpm` behavior with little or no change to [netcdf-interfaces]?

[netcdf-interfaces]: https://github.com/LKedward/netcdf-interfaces
[inference-engine]: https://go.lbl.gov/inference-engine

### Possible Solution

I'm thinking of submitting a pull request against [netcdf-interfaces] with

1. An `options.rsp` file containing `fpm` options and
2. A modified `README.md` adding `@options` to the `fpm` command in the build instructions.

On a related note, it might be nice to be able to choose a specific `--profile` for a specific dependency without impacting the `--profile` for the rest of the project.  Are there better approaches?

**Comment by perazz** [comment]
As of fpm 0.8, implicit typing is disabled by default on all packages. 

It can be turned back on in the manifest: 
https://fpm.fortran-lang.org/en/spec/manifest.html#fortran-features

though I don't know what's the effect on predefined profiles
