### ISSUE TITLE
temporary directory not recognized

### ISSUE THREAD

**Issue by perazz** [fortran-lang/fpm#905]
### Description

see discussion at [Fortran Discourse](https://fortran-lang.discourse.group/t/fpm-version-0-8-2-released-centralized-registry/5792/2).

### Expected Behaviour

`/tmp` is a standard temporary folder.

### Version of fpm

0.8.2

### Platform and Architecture

Ubuntu 22.04

**Comment by vmagnin** [comment]
Same problem on:

- Linux Ubuntu 23.04
- Linux Fedora 38
