### ISSUE TITLE
Should display fpm logo in github topics

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#908]
https://github.com/topics/fortran-package-manager shows every package in github with the fortran-package manager. fpm has a logo;
it seems it should appear there.  It is set by going to the little gear (or whatever it is) over the topics and adding the logo there.

Many of the other logos there are eye-catching; which I think proves the point the fpm logo should be added.

**Comment by awvwgk** [comment]
See https://github.com/github/explore/blob/main/CONTRIBUTING.md#curating-a-new-topic-or-collection for instructions.

**Comment by urbanjost** [comment]
https://github.com/topics/fortran-package-manager

appears to be there.
