### ISSUE TITLE
Since 0.8.x (?) fetching from Github is semi-broken and in many cases fails

### ISSUE THREAD

**Issue by barracuda156** [fortran-lang/fpm#909]
### Description

Problem looks like this:
```
Executing:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_fpm/fpm/work/fpm-0.8.1" && FPM_CFLAGS="-Os -arch x86_64" FPM_LDFLAGS="-L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64" /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_fpm/fpm/work/fpm-0.8.1/install.sh 
DEBUG: system:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_fpm/fpm/work/fpm-0.8.1" && FPM_CFLAGS="-Os -arch x86_64" FPM_LDFLAGS="-L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64" /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_fpm/fpm/work/fpm-0.8.1/install.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   280  100   280    0     0   1404      0 --:--:-- --:--:-- --:--:--  1465
Could not fetch the latest release from GitHub. Install curl or wget, and ensure network connectivity.
Command failed:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_fpm/fpm/work/fpm-0.8.1" && FPM_CFLAGS="-Os -arch x86_64" FPM_LDFLAGS="-L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64" /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_fpm/fpm/work/fpm-0.8.1/install.sh 
Exit code: 3
Error: Failed to build fpm: command execution failed
```

Example one: https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/136455/steps/install-port/logs/stdio
Example two, right now: https://github.com/macports/macports-ports/actions/runs/4957808218/jobs/8869925225?pr=18637

At the same time another build bot worked fine with identical portfile: https://github.com/macports/macports-ports/actions/runs/4957808218/jobs/8869925080?pr=18637

Of course, `curl` is available, so configure script is lying.

### Expected Behaviour

It should reliably work. _Ideally the build should not depend on fetching anything._

### Version of fpm

0.8.2

### Platform and Architecture

macOS

### Additional Information

Macports portfile: https://github.com/macports/macports-ports/blob/48985779d5951c826997e62b5e37a9c866c9db46/devel/fpm/Portfile

**Comment by perazz** [comment]
Had the same issue with the fpm CI on the macOS-11 images. 
the script uses wget/curl to fetch the latest release tag from github. It only happens sometimes and on macOS11, which tells me there should be something specific to the github runner, probably with network connectivity.

**Comment by barracuda156** [comment]
I think there should be an option not to fetch anything and install exactly that version which is supposed to be installed, without smuggling in an update :)

**Comment by perazz** [comment]
Fpm is built with fpm, that’s why the installer downloads the latest available single-file source as a “bootstrapper” fpm. Maybe it would make sense to include such file into the next release repository directly, that would save the installer from having to download it. I don’t know what’s the thought from other @fortran-lang/admins

**Comment by barracuda156** [comment]
> Fpm is built with fpm

Hmm, how does it build for platforms for which binaries are not available? I have it built and working on Darwin PPC, and I am sure there are no pre-built binaries for it with upstream.

**Comment by barracuda156** [comment]
> It only happens sometimes and on macOS11
> 
> [actions/runner-images#4896](https://github.com/actions/runner-images/issues/4896)

By the way, no, it is not specific to macOS 11 (and yes, does not _necessarily_ happen on macOS 11), see Macports logs here: https://ports.macports.org/port/fpm/details (notice which OS fail there).

**Comment by perazz** [comment]
> > Fpm is built with fpm
> 
> Hmm, how does it build for platforms for which binaries are not available? I have it built and working on Darwin PPC, and I am sure there are no pre-built binaries for it with upstream.

First, the latest release (single-file version) is downloaded and built; then, it’s used to build the current version

**Comment by barracuda156** [comment]
> > > Fpm is built with fpm
> > 
> > 
> > Hmm, how does it build for platforms for which binaries are not available? I have it built and working on Darwin PPC, and I am sure there are no pre-built binaries for it with upstream.
> 
> First, the latest release (single-file version) is downloaded and built; then, it’s used to build the current version

Ah, yes I remember.

**Comment by barracuda156** [comment]
@perazz Possibly, it is recent updates to `install.sh` broken it – `get_latest_release` does not work reliably.
Like this is builds fine: https://github.com/macports/macports-ports/pull/18637/files
