### ISSUE TITLE
Only compile tests for fpm test command

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm#92]
`cargo build` does not build tests. You have to do `cargo build --tests` to also build tests.

`cargo test` build tests (if needed) and runs them.

I suggest we follow the same approach.

**Comment by awvwgk** [comment]
How would we implement this behaviour? Would we remove the tests when building the model from the manifest or should we just filter them out from the targets?

**Comment by certik** [comment]
Model should have everything. Then in `fpm build` you only build the main program but not tests. That can be achieved with multiple approaches, either removing the tests from the model, or by skipping them when building.

**Comment by LKedward** [comment]
> How would we implement this behaviour? Would we remove the tests when building the model from the manifest or should we just filter them out from the targets?

I agree and would suggest keeping everything in the model and simply filtering them out with additional arguments when building the target list in [`build_target_list`](https://github.com/fortran-lang/fpm/blob/6bbb3071bc4a7959071642c7a06942d8d784af7c/src/fpm_targets.f90#L153)
