### ISSUE TITLE
error message shows module_naming instead of module-naming

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#931]
### Description

src/fpm/cmd/publish.f90:      & 'Please set "module_naming = true" in fpm.toml [build] or specify a custom module prefix.')

the message should have module-naming, not module_naming.

### Expected Behaviour

expect correct manifest option to be displayed

### Version of fpm

>=v0.9.0

### Platform and Architecture

all

**Comment by perazz** [comment]
https://github.com/fortran-lang/fpm/blob/c9072d9241062c07d5277d9494b393e355f2d1ad/src/fpm/cmd/publish.f90#L50

@minhqdao
