### ISSUE TITLE
string length exceeded in several locations, preventing building with bounds checks on

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm#934]
### Description

The jonquil dependency exceeds substring bounds in multiple places. 
For example:

   At line 184 of file build/dependencies/jonquil/src/jonquil/lexer.f90
   Fortran runtime error: Substring out of bounds: upper bound (712) of 'lexer' exceeds string length (711)

Examples where this occurs:

lexer.f90:      do while(any(lexer%chunk(pos+1:pos+1) == [" ", toml_escape%tabulator, &
lexer.f90:   do while(verify(lexer%chunk(pos+1:pos+1), terminated) > 0 .and. pos < len(lexer%chunk))
lexer.f90:   do while(verify(lexer%chunk(pos+1:pos+1), terminated) > 0 .and. pos < len(lexer%chunk))

### Expected Behaviour

Should be able to build with bounds checks on and still use fpm(1)

### Version of fpm

>=v0.9.0

### Platform and Architecture

all

**Comment by perazz** [comment]
Thank you @urbanjost. I think the best strategy to fix this is to submit a patch to the jonquil repository (see https://github.com/toml-f/jonquil/issues/15)
To do this, we need at least one example of a toml/json input stream that causes that issue. I haven't been able to find one thus far.

**Comment by urbanjost** [comment]
Any repository dependency will trigger it. 
```
fpm new /tmp/A
cd /tmp/A
# add a repository dependency to the fpm.toml file
fpm build
```

An example fpm.toml file that triggers the bug:


[fpm.toml](https://github.com/fortran-lang/fpm/files/11714403/fpm.toml.txt)
