### ISSUE TITLE
Unable to use the `mpi` metapackage

### ISSUE THREAD

**Issue by yuxuan-z19** [fortran-lang/fpm#970]
### Description

Errors are raised while including `mpi` as `[dependencies]`

```bash
$ fpm build
 + which mpiexec
/usr/bin/mpiexec
<ERROR> *cmd_build* Model error: metapackage fortran error: metapackage does require implicit-external, main package does not
STOP 1
```

`fpm.toml` is configured as shown below:

```toml
# fpm.toml
[dependencies]
openmp = "*"
mpi = "*"
```

### Expected Behaviour

```bash
$ fpm build
 + which mpiexec
/usr/bin/mpiexec
<ERROR> *cmd_build* Model error: metapackage fortran error: metapackage does require implicit-external, main package does not
STOP 1
```

### Version of fpm

0.9.0, alpha

### Platform and Architecture

Ubuntu 22.04

**Comment by perazz** [comment]
MPI metapackage currently encompasses all versions including the old `mpif.h` F77 wrappers, as no version requirements are implemented yet. Hence, it is necessary to turn off the Modern Fortran implicit typing defaults as: 

```
[fortran]
implicit-external=true
implicit-typing=true
```

**Comment by luflarois** [comment]
Hi @perazz 

I had the same problem. And I made the same, my example:

```toml
name = "demo"

[fortran]
implicit-external=true
implicit-typing=true

[dependencies]
mpi = "*"
```
When I try compile my example I got the following error:

```bash
/opt/bin/fpm build --compiler 'mpif90'                                
 + which mpiexec
/opt/gnu/bin/mpiexec
 + mkdir -p build/dependencies
<ERROR> *cmd_build* Target error: Unable to find source for module dependency: "mpi" used by "app/main.f90"
STOP 1
```
Do You  know what happens?

**Comment by perazz** [comment]
If you're using `fpm <= 0.9`, and you `use mpi` or `use mpi_f08` in your code, you should add these modules to the list of external modules in your fpm.toml: 

```toml
external-modules = ["mpi","mpi_f08"]
```

If you're using `fpm >= 0.10.0`, no need to add them as external modules: they will be handled internally.

**Comment by luflarois** [comment]
I am using 0.9, 

```bash
/opt/bin/fpm --version                                                                (base)
Version:     0.9.0, alpha
Program:     fpm(1)
Description: A Fortran package manager and build system
Home Page:   https://github.com/fortran-lang/fpm
License:     MIT
OS Type:     Linux
```

where I must add the directive external-modules? Inside "dependencies"?

**Comment by luflarois** [comment]
error:
```bash
/opt/bin/fpm build --compiler 'mpif90' --flag -I/opt/gnu/include                        (base)
<ERROR> *cmd_build* Package error: Dependency external-modules must be a table entry
STOP 1

```

**Comment by perazz** [comment]
It should be under `[build]`:

```toml
[build]
external-modules = ["mpi", "mpi_f08"]  
```

**Comment by luflarois** [comment]
Now its working! Thanks a lot!
