### ISSUE TITLE
[i386] Build error: `Undefined symbols for architecture i386: "_opendir$INODE64"`

### ISSUE THREAD

**Issue by barracuda156** [fortran-lang/fpm#993]
### Description

Trying to build FPM on macOS i386 resulted in linking error:
```
Undefined symbols for architecture i386:
  "_opendir$INODE64", referenced from:
      _c_opendir in libfpm.a(src_filesystem_utilities.c.o)
ld: symbol(s) not found for architecture i386
collect2: error: ld returned 1 exit status
<ERROR> Compilation failed for object " fpm "
<ERROR> stopping due to failed compilation
STOP 1
Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_fpm/fpm/work/fpm-0.10.0" && FPM_CFLAGS="-Os -arch i386" FPM_LDFLAGS="-L/opt/local/lib -Wl,-headerpad_max_install_names -arch i386" /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_fpm/fpm/work/fpm-0.10.0/install.sh 
Exit code: 1
```

### Expected Behaviour

Hopefully, it can be made to build, since it not only builds but also works on 32-bit PowerPC (tested on the same 10.6 build 10A190).

### Version of fpm

0.10.0

### Platform and Architecture

macOS 10.6 / i386

### Additional Information

Macports build env.
See also: https://trac.macports.org/ticket/69278

**Comment by barracuda156** [comment]
Here is what `libSystem` has:
```
$ nm -arch i386 /usr/lib/libSystem.B.dylib | grep opendir
00081276 T ___opendir2
0006942b T ___opendir2$INODE64$UNIX2003
0002804a T ___opendir2$UNIX2003
0007ec14 T _opendir
00069410 T _opendir$INODE64$UNIX2003
0002802f T _opendir$UNIX2003
```
Here is what `fpm` sets:
```
#if defined(__APPLE__) && !defined(__aarch64__) && !defined(__POWERPC__)
DIR * opendir$INODE64( const char * dirName );
struct dirent * readdir$INODE64( DIR * dir );
#define opendir opendir$INODE64
#define readdir readdir$INODE64
#endif
```
This PR added exclusion for PowerPC: https://github.com/fortran-lang/fpm/pull/824
This PR for arm64: https://github.com/fortran-lang/fpm/issues/547

In fact I am not completely sure we fixed it earlier in a correct way even for PowerPC. Notice:
```
$ nm -arch ppc /usr/lib/libSystem.B.dylib | grep opendir
000a0118 T ___opendir2
0008119c T ___opendir2$INODE64$UNIX2003
0000e1c8 T ___opendir2$UNIX2003
0009ca4c T _opendir
00081194 T _opendir$INODE64$UNIX2003
0000e1c0 T _opendir$UNIX2003
```
Even though `fpm` appears to work fine on `ppc` with existing code. (At least, no related errors were seen, and I do build a number of ports using `fpm` for `ppc`.)

There are two questions:
1. For 32-bit archs (`ppc` and `i386`), should we actually skip the block or use it in a modified way?
2. For `ppc64`, likely, INODE64 should be used, though I cannot check symbols in the libSystem right now (to be updated). If yes, then condition should refer to `__ppc__`, not `__POWERPC__`.

@awvwgk What do you think?

**Comment by barracuda156** [comment]
UPD. 10.5.8 has INODE64 version for `ppc64`:
```
sergey-fedorovs-mac-mini:~ svacchanda$ nm -arch ppc64 /Volumes/Leopard/usr/lib/libSystem.B.dylib  | grep opendir
00000000000a7034 T ___opendir2
0000000000117070 T ___opendir2$INODE64
00000000000a422c T _opendir
00000000001174a8 T _opendir$INODE64
```

**Comment by kencu** [comment]
Apple's official method to test for a 64 bit build is to check for ```__LP64__``` being defined, eg:

https://forums.developer.apple.com/forums/thread/85816

Using ```__ppc__``` to test for a 32 bit powerpc build but not a 64bit powerpc build seems pretty obscure, and also rather fragile to remember a few months or years later... testing for 32 bit builds by testing for ```__i386__``` works, but only for Intel builds of course.

So another way to have tested this here, arguably more clear and easier to remember for the future, would have been:

```
#if defined(__APPLE__) && defined(__LP64__) && !defined(__aarch64__)
```

(I haven't personally verified the ```__aarch64``` availability of these symbols as yet, but see that was there before, so apparently someone did.)

**Comment by barracuda156** [comment]
@kencu Thank you, your suggestion looks good. Does `__LP64__` work for all relevant compilers on macOS (gcc and clang)?

**Comment by kencu** [comment]
Indeed, it is supposed. The oldest one to double check is gcc-4.2.
