### ISSUE TITLE
--flag doesn't override the default flags even without --profile

### ISSUE THREAD

**Issue by rouson** [fortran-lang/fpm#998]
### Description

`fpm --help` reports "--flag  FFLAGS  selects compile arguments for the build, the default value is set by the FPM_FFLAGS environment variable. These are added to the profile options if --profile is specified, else these options override the defaults..."  But the following transcript excerpt appears to demonstrate otherwise:
```
fpm new hello
cd hello
fpm build --flag "-O1" --verbose
```
whereupon I see output that includes lines like 
```
gfortran -c ././src/hello.f90   -O1 -fimplicit-none -Werror=implicit-interface -ffree-form -J build/gfortran_2866DEF92F2F6F01 -Ibuild/gfortran_2866DEF92F2F6F01 -o build/gfortran_2866DEF92F2F6F01/hello/src_hello.f90.o
```
I'm attempting to build some code that uses fixed-source form, implicit typing, and implicit interfaces.  I plan to switch the code to free-source form with no implicit typing and no implicit interfaces, but I didn't write the code so I'd prefer to be able to build the code as is and write tests that will verify that my changes don't break anything.  So at least initially, I'd like to override the `fpm`'s  default flags, namely `-fimplicit-none -Werror=implicit-interface -ffree-form`.

### Expected Behaviour

I expected that passing `--flag "-O1"` would override the default flags.

### Version of fpm

 0.10.0

### Platform and Architecture

macOS/Arm

### Additional Information

I also tried setting `FPM_FFLAGS` and that didn't override the defaults either.

**Comment by rouson** [comment]
This behavior started with version 0.8.0.   Version 0.7.0 behaves as expected in accordance with my interpretation of the output of `fpm --help`.

**Comment by perazz** [comment]
I believe you're looking for Fortran features support in `fpm.toml`: https://github.com/fortran-lang/fpm/pull/864 , they were introduced in 0.8.0.

Documentation: https://fpm.fortran-lang.org/spec/manifest.html#implicit-typing

```toml
[fortran]
implicit-typing = true  # default: false
implicit-external = true  # default: false
source-form = "fixed"  # "free" (default), or "default" (compiler default)
```

**Comment by rouson** [comment]
@perazz thanks! I think we should also change the language in the `fpm --help` output.

**Comment by rouson** [comment]
PR #999 addresses this issue.

**Comment by rouson** [comment]
> I believe you're looking for Fortran features support in `fpm.toml`: #864 , they were introduced in 0.8.0.
> 
> Documentation: https://fpm.fortran-lang.org/spec/manifest.html#implicit-typing
> 
> ```toml
> [fortran]
> implicit-typing = true  # default: false
> implicit-external = true  # default: false
> source-form = "fixed"  # "free" (default), or "default" (compiler default)
> ```

Is there a way to apply a Fortran configuration to a subset of files or does it have to be global?  It seems my intended scenario isn't supported: progressively modernizing a legacy package.

**Comment by perazz** [comment]
Thank you @rouson for the fix, if you think this issue is closed as far as you're concerned, let's close also this page soon.

**Comment by rouson** [comment]
Done.
